#!/usr/bin/env node
// COS-42 endpoint behaviour. No network: the persistence boundary is injected.
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import {
  composeResolutionView, handleResolutionViewRequest, handleResolutionReviewRequest,
  publicDurableProjectionReceipts, publicExternalIdentitySupport
} from "../api/csm-resolution-view.js";
import {
  CAPTURED_E1AE_RESOLUTION_REVIEW_VERSION,
  REVIEW_VERDICT,
  CORRECTION_REASON
} from "../lib/listing/csm/resolution-review.mjs";
import { parseCanonicalFields } from "../lib/listing/thin/canonical-fields.mjs";
import { SEM_STANDARD_VERSION } from "../lib/listing/csm/sem-definition.mjs";
import { composeFromCanonicalFields } from "../lib/listing/thin/canonical-composer.mjs";
import {
  composeLyncaStandardName,
  LYNCA_STANDARD_PROFILE_VERSION_V1,
  LYNCA_STANDARD_PROFILE_VERSION_V2,
  LYNCA_STANDARD_PROFILE_VERSION_V3
} from "../lib/listing/thin/canonical-naming-adapter.mjs";
import {
  buildCsmStageRows,
  computeCsmPacketHashes,
  EBAY_PROFILE_VERSION,
  THIN_COMPOSER_VERSION,
  THIN_COMPOSER_VERSION_V1,
  THIN_COMPOSER_VERSION_V2
} from "../lib/listing/thin/csm-persistence.mjs";
import { composeCanonicalFieldsForStoredOutput } from
  "../lib/listing/thin/csm-replay.mjs";
import { readCsmResolutionRecord } from "../lib/listing/thin/csm-supabase-writer.mjs";
import {
  CSM_OWNER_EXECUTION_RECEIPT_KEYS,
  CSM_OWNER_EXECUTION_RECEIPT_VERSION,
  sealCsmOwnerExecutionReceipt
} from "../lib/listing/thin/csm-owner-execution-receipt.mjs";
import {
  EXTERNAL_IDENTITY_REPLAY_COMPATIBILITY_REGISTRY,
  EXTERNAL_IDENTITY_SUPPORT_PACK
} from "../lib/listing/knowledge/csm-external-identity-support.mjs";

const OWNER_RECEIPT_SHA256 = "b".repeat(64);
const sha256Json = (value) => createHash("sha256")
  .update(JSON.stringify(value))
  .digest("hex");
const noSearchDurableReceipts = (fields) => ({
  founderBetaWebReceipt: {
    schema_version: "founder-beta-web-receipt-v1",
    provider_request_count: 1,
    isolated_model_call_count: 0,
    provider_model: "gpt-5.6-luna",
    reasoning_effort: "low",
    web_search_used: false,
    web_search_call_count: 0,
    queries: [],
    urls: [],
    field_evidence: [],
    semantic_state_sha256: "d".repeat(64)
  },
  setCardNameRelationReceipt: {
    schema_version: "set-card-name-relations-v1",
    set: fields.set
      ? { predicate: "CURRENT_CARD_MEMBER_OF_SET", value: fields.set } : null,
    card_name: fields.card_name
      ? { predicate: "CURRENT_CARD_NAMED_BY_DESIGN", value: fields.card_name } : null
  }
});
const webSearchDurableReceipts = (fields) => ({
  founderBetaWebReceipt: {
    schema_version: "founder-beta-web-receipt-v1",
    provider_request_count: 1,
    isolated_model_call_count: 0,
    provider_model: "gpt-5.6-luna",
    reasoning_effort: "low",
    web_search_used: true,
    web_search_call_count: 1,
    queries: ["2020-21 Panini Contenders Anthony Edwards #105 checklist"],
    urls: ["https://www.paniniamerica.net/checklist"],
    field_evidence: [{
      field: "card_name",
      support_urls: ["https://www.paniniamerica.net/checklist"],
      conflict_urls: [],
      unresolved_urls: []
    }],
    semantic_state_sha256: "e".repeat(64)
  },
  setCardNameRelationReceipt: noSearchDurableReceipts(fields)
    .setCardNameRelationReceipt
});

// Full HTTP-response byte fingerprints generated by the archived de55
// Production reader. The bridge may expand its readable tuple set, but the
// already-published v2 projection must remain byte-identical for every active
// grammar, including array order and omitted keys.
const DE55_LEGACY_FLAT_VIEW_SHA256 = Object.freeze({
  standard: "63bb05a24aa2012723c7723c519d2b5a2dc63e529bfd486660b214ad11d64f0a",
  tcg: "67b6090ba45f2e2ec69488d7104951365ad1da0d3d6face806073dde0ddd2d8d",
  lot: "b04e3e157c29996926ca52147e573df3dc87a7a014b1fab54a464a0ab0027520"
});
const DE55_LEGACY_REPLAY_VIEW_SHA256 =
  "4d251b80cf67f595133b83fb93e68ae9d07315ad8f1d89c9307fcf05736a85a3";
const DE55_V1_REPLAY_VIEW_SHA256 =
  "70c79a47c59047db1180ed2d3f88f4e0b36359c8c7edc3a51b098822d2125b21";

const payload = JSON.stringify({
  year: "2025", manufacturer: "Topps", product: "Chrome", set: "", card_name: "",
  release_variant: "", surface_color: "Gold", parallel_family: "Refractor", parallel_exact: "",
  descriptive_rarity: "", subjects: ["Shohei Ohtani"], team: "Dodgers", card_number: "150",
  serial: "17/50", attributes: ["RC"], grading_info: null, grammar: "standard",
  lot_count: "", language: "", unreadable: [], low_confidence: []
});
const record = {
  asset_id: "asset-1", recognition_session_id: "sess-1", resolution_id: "res-1",
  output_id: "out-1", canonical_payload: payload,
  output_title: composeResolutionView({ canonical_payload: payload }).composed.title,
  resolver_version: "thin-path-observation-only-v1",
  owner_execution_receipt: {
    version: CSM_OWNER_EXECUTION_RECEIPT_VERSION,
    sha256: OWNER_RECEIPT_SHA256,
    provider_response_id: "must-not-leave-the-server"
  }
};
const deps = { readRecord: async () => record, appendReview: async ({ review }) => review };
const futureReviewFields = parseCanonicalFields(JSON.parse(payload)).fields;
const futureReviewComposed = composeLyncaStandardName(futureReviewFields, {
  publicationCoverage: true
});
const futureReviewRows = buildCsmStageRows({
  tenantId: "t1",
  recognitionSessionId: "sess-future-review",
  fields: futureReviewFields,
  composed: futureReviewComposed,
  title: futureReviewComposed.title,
  ...noSearchDurableReceipts(futureReviewFields)
});
const futureReviewRecord = {
  asset_id: "asset-future-review",
  recognition_session_id: "sess-future-review",
  resolution_id: futureReviewRows.resolution.id,
  output_id: futureReviewRows.output.id,
  output_title: futureReviewComposed.title,
  resolver_version: futureReviewRows.resolution.resolver_version,
  replay_rows: futureReviewRows
};
const futureReviewDeps = {
  readRecord: async () => futureReviewRecord,
  appendReview: async ({ review }) => review
};

// Flat records have no historical replay bundle, so their stored pair must
// equal the active router pair for their grammar. Activation A moves only
// Standard to v3/v0.2; TCG and Lot remain on v2/eBay.
const legacyFlatCases = [
  ["tcg", {
    year: "2025", product: "Pokemon", set: "Mega Brave",
    subjects: ["Mega Absol Ex"], card_number: "089/063",
    grammar: "tcg", language: "JP", ip: "Pokemon"
  }],
  ["lot", {
    year: "2023", manufacturer: "Panini", product: "Prizm",
    subjects: ["Victor Wembanyama", "LeBron James"],
    grammar: "lot", lot_count: "2"
  }]
];
for (const [grammar, canonicalPayload] of legacyFlatCases) {
  const current = composeResolutionView({
    canonical_payload: JSON.stringify(canonicalPayload),
    composer_version: THIN_COMPOSER_VERSION_V2,
    marketplace_profile_version: EBAY_PROFILE_VERSION
  });
  assert.equal(current.composed.grammar, grammar);
  assert.equal(current.composer_version, THIN_COMPOSER_VERSION_V2);
  assert.equal(current.marketplace_profile_version, EBAY_PROFILE_VERSION);

  const legacyRecord = {
    asset_id: `asset-${grammar}`,
    recognition_session_id: `session-${grammar}`,
    resolution_id: `resolution-${grammar}`,
    output_id: `output-${grammar}`,
    canonical_payload: JSON.stringify(canonicalPayload),
    output_title: current.composed.title,
    resolver_version: "thin-path-observation-only-v1",
    owner_execution_receipt: {
      version: CSM_OWNER_EXECUTION_RECEIPT_VERSION,
      sha256: OWNER_RECEIPT_SHA256
    }
  };
  const publicView = await handleResolutionViewRequest({
    tenantId: "t1",
    assetId: legacyRecord.asset_id,
    dependencies: { readRecord: async () => legacyRecord }
  });
  assert.equal(sha256Json(publicView), DE55_LEGACY_FLAT_VIEW_SHA256[grammar],
    `${grammar} v2 public bytes must remain exact to de55 Production`);
  assert.equal(Object.hasOwn(publicView.composer, "marketplace_profile_version"), false);
  assert.ok(publicView.brackets.every((entry) => !Object.hasOwn(entry, "canonical_fields")));
}

// New durable Lot rows expose terminal review state without changing archived
// de55 flat/replay bytes. These are diagnostic stored titles, never usable-200
// writer responses; the direct route refuses them after atomic persistence.
for (const [name, lotCount, expected] of [
  ["unresolved", "", "LOT_QUANTITY_UNRESOLVED"],
  ["single", "1", "LOT_SINGLE_CARD"]
]) {
  const fields = parseCanonicalFields({
    manufacturer: "Topps", product: "Chrome", subjects: ["A", "B"],
    grammar: "lot", lot_count: lotCount
  }).fields;
  const raw = composeFromCanonicalFields(fields, { features: {
    durable_lot_terminal_shared_only: true,
    publication_coverage: true
  } });
  const composed = {
    ...raw,
    lot_publishable: false,
    lot_publication_failure_code: expected
  };
  const rows = buildCsmStageRows({
    tenantId: "t1", recognitionSessionId: `lot-${name}-session`,
    fields, composed, title: composed.title, ...noSearchDurableReceipts(fields)
  });
  const view = await handleResolutionViewRequest({
    tenantId: "t1", assetId: `lot-${name}-asset`,
    dependencies: { readRecord: async () => ({
      asset_id: `lot-${name}-asset`, recognition_session_id: `lot-${name}-session`,
      resolution_id: rows.resolution.id, output_id: rows.output.id,
      output_title: composed.title, resolver_version: rows.resolution.resolver_version,
      replay_rows: rows
    }) }
  });
  assert.equal(view.lot_terminal.publishable, false);
  assert.equal(view.lot_terminal.failure_code, expected);
  assert.equal(view.lot_terminal.lot_quantity_unresolved, name === "unresolved");
  assert.equal(view.lot_terminal.lot_single_card, name === "single");
}
{
  const currentStandard = composeResolutionView({
    canonical_payload: payload,
    composer_version: THIN_COMPOSER_VERSION,
    marketplace_profile_version: LYNCA_STANDARD_PROFILE_VERSION_V2
  });
  assert.equal(currentStandard.composer_version, THIN_COMPOSER_VERSION);
  assert.equal(currentStandard.marketplace_profile_version,
    LYNCA_STANDARD_PROFILE_VERSION_V2);
  const activeRecord = {
    asset_id: "asset-standard-active",
    recognition_session_id: "session-standard-active",
    resolution_id: "resolution-standard-active",
    output_id: "output-standard-active",
    canonical_payload: payload,
    output_title: currentStandard.composed.title,
    composer_version: THIN_COMPOSER_VERSION,
    marketplace_profile_version: LYNCA_STANDARD_PROFILE_VERSION_V2,
    resolver_version: "thin-path-observation-only-v1",
    owner_execution_receipt: {
      version: CSM_OWNER_EXECUTION_RECEIPT_VERSION,
      sha256: OWNER_RECEIPT_SHA256
    }
  };
  const activeView = await handleResolutionViewRequest({
    tenantId: "t1",
    assetId: activeRecord.asset_id,
    dependencies: { readRecord: async () => activeRecord }
  });
  assert.equal(activeView.composer.composer_version, THIN_COMPOSER_VERSION);
  assert.equal(activeView.composer.marketplace_profile_version,
    LYNCA_STANDARD_PROFILE_VERSION_V2);

  assert.throws(() => composeResolutionView({
    canonical_payload: payload,
    composer_version: THIN_COMPOSER_VERSION_V2,
    marketplace_profile_version: EBAY_PROFILE_VERSION
  }), (error) => error?.statusCode === 409
    && error?.message === "csm_resolution_replay_rows_required");
}
for (const marketplaceProfileVersion of [
  LYNCA_STANDARD_PROFILE_VERSION_V1,
  LYNCA_STANDARD_PROFILE_VERSION_V3
]) {
  assert.throws(
    () => composeResolutionView({
      canonical_payload: payload,
      composer_version: THIN_COMPOSER_VERSION,
      marketplace_profile_version: marketplaceProfileVersion
    }),
    (error) => error?.statusCode === 409
      && error?.message === "csm_resolution_replay_rows_required",
    `a Standard v3/${marketplaceProfileVersion} flat record requires its replay rows`
  );
}

const legacyPayload = {
  year: "2018", manufacturer: "Topps", product: "Topps Silver Pack", set: "",
  subjects: ["Shohei Ohtani"], team: "", card_name: "1983 Chrome Promo",
  release_variant: "", surface_color: "Blue", parallel_family: "Refractor",
  parallel_exact: "Blue Refractor", descriptive_rarity: "", card_number: "",
  serial: "018/150", attributes: ["RC"], grading_info: {
    company: "PSA", card_grade: "10", auto_grade: "", grade_type: "CARD_ONLY"
  }, grammar: "standard", lot_count: "", language: "", unreadable: [], low_confidence: []
};
const legacyFields = parseCanonicalFields(legacyPayload).fields;
const legacyComposed = composeFromCanonicalFields(legacyFields, {
  features: { exact_parallel_color_compaction: false, publication_coverage: false }
});
const legacyRows = buildCsmStageRows({
  tenantId: "t1", recognitionSessionId: "legacy-session",
  fields: legacyFields, composed: legacyComposed, title: legacyComposed.title,
  contractVersion: "csm-stage-shadow-v2"
});
legacyRows.output.composer_version = THIN_COMPOSER_VERSION_V1;
legacyRows.output.title = legacyComposed.title;
legacyRows.resolution.recognition_packet_sha256 = computeCsmPacketHashes(legacyRows)
  .csm_recognition_packet_sha256;
legacyRows.output.resolution_packet_sha256 = computeCsmPacketHashes(legacyRows)
  .csm_resolution_packet_sha256;
legacyRows.session_hashes = computeCsmPacketHashes(legacyRows);
const legacyRecord = {
  asset_id: "legacy-asset", recognition_session_id: "legacy-session",
  resolution_id: legacyRows.resolution.id, output_id: legacyRows.output.id,
  output_title: legacyComposed.title, composer_version: THIN_COMPOSER_VERSION_V1,
  resolver_version: "thin-path-observation-only-v1", replay_rows: legacyRows
};

// The first published eBay Lot writer used `LotxN`; the e1ae reader already
// replayed those immutable rows as `Lot*N` (and omitted a one-card marker).
// Freeze both sides of that intentional split through GET and review so an
// integrity hardening cannot silently rewrite the public historical contract.
{
  const expected = Object.freeze({
    "": Object.freeze({
      output_id: "b275ced06c169a90ab3eac1e11ff3830",
      get: "9de819f82c7a669ba1a4c0a3eb040b5a43d6e7d204ebce3b35cd45bf1baeb316",
      approved: "048ad1f8e51f2291e65fcea322da7756c2fb09d2ffc94419776fe39614b4a5eb",
      corrected: "b654e6aff3368097bd8b3076794842f2c07448ddaf10a6d0dff4f9d41d056495"
    }),
    "1": Object.freeze({
      output_id: "e40311a180863ecebc22e01a8d5ba5cc",
      get: "5dcdc2aa17c458190e01d5d7a2289c694789953f298358191c9884d1d4d337ae",
      approved: "8dfb3d292428c50f62a587d7817139b5026647864dd4fa230146503b5bc5341f",
      corrected: "e0196712ffd57747586a33851edaec816c0d7666f9d7bf81b62d52bc9f64c672"
    }),
    "2": Object.freeze({
      output_id: "ce383240ebb1edb5e00af55ffa836938",
      get: "3360b6a48a9873766226d58a6c2861b054bc1e42a1dfd417c235bcef788bd582",
      approved: "c018ebc5172497a801172178499857921a30740fa3dcc1a5d16d4db306ea023a",
      corrected: "f290d991696a16b1c2c168e52c5a18a201a6c6e3b7974336220e9cbed56dce09"
    }),
    "4": Object.freeze({
      output_id: "95c74124413da89b62791a6481bcebd7",
      get: "a83c31c27cf7b0b5fa8b9e209ab32d91196abeda2ff1aee70d25bc2ccd3a40a2",
      approved: "5b3db6c14c154c7b462679274602f3a70d8ef37a11557a1cd635d85949271b3f",
      corrected: "e9d115f5b7a5ae45fe20f5817eecf9f2d817959c789986dea9761e170714f350"
    })
  });
  const nativeDate = globalThis.Date;
  globalThis.Date = class FixedReviewDate extends nativeDate {
    constructor(...args) {
      super(...(args.length ? args : ["2026-08-14T00:00:00.000Z"]));
    }
    static now() { return new nativeDate("2026-08-14T00:00:00.000Z").getTime(); }
  };
  try {
    for (const count of ["", "1", "2", "4"]) {
      const id = `v1_lot_${count || "missing"}`;
      const fields = parseCanonicalFields({
        year: "2023", manufacturer: "Topps", product: "Chrome", set: "",
        subjects: ["Shohei Ohtani", "Mike Trout"], team: "", card_name: "",
        release_variant: "", surface_color: "", parallel_family: "", parallel_exact: "",
        descriptive_rarity: "", card_number: "", serial: "", attributes: ["RC"],
        grading_info: { company: "", card_grade: "", auto_grade: "", grade_type: "" },
        grammar: "lot", lot_count: count, language: "", unreadable: [], low_confidence: [],
        special_stamp: "", description: ""
      }).fields;
      const writerComposed = composeFromCanonicalFields(fields, { features: {
        captured_composer_v1_lot_marker: true,
        exact_parallel_color_compaction: false,
        durable_lot_terminal_shared_only: false,
        publication_coverage: false
      } });
      const stagedComposed = ["", "1"].includes(count) ? {
        ...writerComposed,
        lot_publishable: false,
        lot_publication_failure_code: count === "1"
          ? "LOT_SINGLE_CARD"
          : "LOT_QUANTITY_UNRESOLVED"
      } : writerComposed;
      const rows = buildCsmStageRows({
        tenantId: `tenant-${id}`, recognitionSessionId: `session-${id}`,
        fields, composed: stagedComposed, title: writerComposed.title,
        createdAt: "2026-08-14T00:00:00.000Z", contractVersion: "csm-stage-shadow-v2"
      });
      // `buildCsmStageRows` remains an active-writer boundary and correctly
      // refuses to mint this retired composer. These two values are frozen
      // from the authentic archived writer fixture; the endpoint hashes below
      // independently bind the complete e1ae reader response.
      rows.output.composer_version = THIN_COMPOSER_VERSION_V1;
      rows.output.id = expected[count].output_id;
      rows.resolution.recognition_packet_sha256 = computeCsmPacketHashes(rows)
        .csm_recognition_packet_sha256;
      rows.output.resolution_packet_sha256 = computeCsmPacketHashes(rows)
        .csm_resolution_packet_sha256;
      rows.session_hashes = computeCsmPacketHashes(rows);
      const stored = {
        asset_id: `asset-${id}`, recognition_session_id: `session-${id}`,
        resolution_id: rows.resolution.id, output_id: rows.output.id,
        output_title: writerComposed.title, resolver_version: rows.resolution.resolver_version,
        replay_rows: rows
      };
      const readRecord = async () => structuredClone(stored);
      const get = await handleResolutionViewRequest({
        tenantId: `tenant-${id}`, assetId: stored.asset_id, dependencies: { readRecord }
      });
      const review = async (verdict, corrections = []) => handleResolutionReviewRequest({
        tenantId: `tenant-${id}`, reviewerId: "reviewer-v1-lot",
        payload: { asset_id: stored.asset_id, verdict, corrections },
        dependencies: { readRecord, appendReview: async ({ review: value }) => value }
      });
      const approved = await review(REVIEW_VERDICT.APPROVED);
      const corrected = await review(REVIEW_VERDICT.CORRECTED, [{
        bracket: "year", canonical_field: "year", reason: CORRECTION_REASON.WRONG_VALUE,
        original_value: "2023", corrected_value: "2022"
      }]);
      assert.equal(sha256Json(get), expected[count].get, `${id} exact e1ae GET bytes`);
      assert.equal(sha256Json(approved), expected[count].approved,
        `${id} exact e1ae APPROVED bytes`);
      assert.equal(sha256Json(corrected), expected[count].corrected,
        `${id} exact e1ae CORRECTED bytes`);
    }
  } finally {
    globalThis.Date = nativeDate;
  }
}

// The complete Standard v3 path keeps independent search terms distinct while
// carrying them through persistence, replay, and the Resolution View bracket.
{
  const fields = {
    year: "2025",
    manufacturer: "Upper Deck",
    product: "Series 1",
    subjects: ["Connor Bedard"],
    components: ["RC"],
    search_optimization: ["Young Guns"],
    team: "Blackhawks",
    card_number: "201",
    serial: "",
    grammar: "standard",
    unreadable: [],
    low_confidence: []
  };
  const composed = composeLyncaStandardName(fields, { publicationCoverage: true });
  const rows = buildCsmStageRows({
    tenantId: "t1",
    recognitionSessionId: "independent-search-resolution",
    fields,
    composed,
    title: composed.title,
    ...noSearchDurableReceipts(fields)
  });
  const projected = composeResolutionView({
    asset_id: "independent-search-asset",
    recognition_session_id: "independent-search-resolution",
    resolution_id: rows.resolution.id,
    output_id: rows.output.id,
    output_title: composed.title,
    resolver_version: "thin-path-observation-only-v1",
    replay_rows: rows
  });
  const row = projected.view.brackets.find((entry) => (
    entry.bracket === "search_optimization"
  ));
  assert.deepEqual(row.canonical_fields, ["components", "search_optimization", "team"]);
  assert.equal(row.value, "RC, Young Guns, Blackhawks");
  assert.equal(row.rendered_text, "RC Young Guns Blackhawks");
  assert.equal(projected.fields.team, "Blackhawks");
  assert.deepEqual(projected.fields.components, ["RC"]);
  assert.deepEqual(projected.fields.search_optimization, ["Young Guns"]);
}

// The public readback exposes only bridge-validated attribution receipts. A
// promoted GET can therefore prove Web/no-Web and Set/Card Name relations with
// zero provider calls, while raw provider trace identifiers remain private.
{
  const fields = parseCanonicalFields({
    year: "2020-21", manufacturer: "Panini", product: "Contenders",
    set: "Rookie Ticket", card_name: "Variation Autograph",
    subjects: ["Anthony Edwards"], card_number: "105", grammar: "standard"
  }).fields;
  const composed = composeLyncaStandardName(fields, { publicationCoverage: true });
  const receipts = webSearchDurableReceipts(fields);
  const rows = buildCsmStageRows({
    tenantId: "t1", recognitionSessionId: "web-receipt-resolution",
    fields, composed, title: composed.title, ...receipts
  });
  rows.output.structured_output.provider_response_id = "must-not-leave-the-server";
  const projected = publicDurableProjectionReceipts(rows);
  assert.deepEqual(projected.founder_beta_web_receipt,
    receipts.founderBetaWebReceipt);
  assert.deepEqual(projected.set_card_name_relation_receipt,
    receipts.setCardNameRelationReceipt);
  assert.equal(projected.founder_beta_web_receipt.web_search_used, true);
  assert.equal(projected.founder_beta_web_receipt.web_search_call_count, 1);
  assert.equal(projected.founder_beta_web_receipt.provider_request_count, 1);
  assert.deepEqual(projected.founder_beta_web_receipt.queries,
    ["2020-21 Panini Contenders Anthony Edwards #105 checklist"]);
  assert.doesNotMatch(JSON.stringify(projected), /must-not-leave-the-server/);

  const tampered = structuredClone(rows);
  tampered.output.structured_output.founder_beta_web_receipt
    .web_search_call_count = 0;
  assert.throws(() => publicDurableProjectionReceipts(tampered), (error) => (
    error?.statusCode === 409
      && error?.message === "csm_resolution_durable_projection_receipt_invalid"
  ));
}

// A real Supabase read reconstructs ordinary v3 relation observations from
// private evidence rows. The final Set/Card Name receipt cannot stand in for
// the observation that authorized it.
{
  const fields = parseCanonicalFields({
    year: "2020-21", manufacturer: "Panini", product: "Contenders",
    set: "Rookie Ticket", card_name: "Variation Autograph",
    subjects: ["Anthony Edwards"], card_number: "105", grammar: "standard"
  }).fields;
  const composed = composeLyncaStandardName(fields, { publicationCoverage: true });
  const rows = buildCsmStageRows({
    tenantId: "tenant-ordinary-v3",
    recognitionSessionId: "session-ordinary-v3",
    fields,
    composed,
    title: composed.title,
    ...noSearchDurableReceipts(fields)
  });
  const read = async (evidence = rows.evidence) => readCsmResolutionRecord({
    tenantId: "tenant-ordinary-v3",
    assetId: "asset-ordinary-v3",
    env: {
      SUPABASE_URL: "https://example.supabase.co",
      SUPABASE_SERVICE_ROLE_KEY: "service-role"
    },
    fetchImpl: async (rawUrl) => {
      const url = new URL(rawUrl);
      if (url.pathname.endsWith("/v4_recognition_sessions")) {
        return new Response(JSON.stringify([{
          id: "session-ordinary-v3", asset_id: "asset-ordinary-v3",
          created_at: "2026-08-14T00:00:00Z", csm_owner_versions: null,
          ...rows.session_hashes
        }]), { status: 200 });
      }
      if (url.pathname.endsWith("/csm_marketplace_outputs")) {
        return new Response(JSON.stringify([rows.output]), { status: 200 });
      }
      if (url.pathname.endsWith("/csm_identity_resolutions")) {
        return new Response(JSON.stringify([rows.resolution]), { status: 200 });
      }
      if (url.pathname.endsWith("/csm_resolved_brackets")) {
        return new Response(JSON.stringify(rows.resolved), { status: 200 });
      }
      if (url.pathname.endsWith("/csm_evidence_observations")) {
        return new Response(JSON.stringify(evidence), { status: 200 });
      }
      if (url.pathname.endsWith("/csm_bracket_candidates")) {
        return new Response(JSON.stringify(rows.candidates), { status: 200 });
      }
      if (url.pathname.endsWith("/csm_candidate_evidence_links")) {
        return new Response(JSON.stringify(rows.links), { status: 200 });
      }
      return new Response("[]", { status: 404 });
    }
  });
  const durable = await read();
  assert.doesNotThrow(() => composeResolutionView(durable),
    "ordinary v3 partial DB read retains exact relation observations");
  const rejectsBrokenPacket = (error) => error?.statusCode === 409
    && error?.message === "csm_resolution_replay_integrity_invalid";

  const missing = await read([]);
  assert.throws(() => composeResolutionView(missing), rejectsBrokenPacket,
    "ordinary v3 readback rejects missing relation evidence");

  const forged = structuredClone(rows.evidence);
  const setVisual = forged.find((row) => (
    row.modality === "WHOLE_CARD_VISUAL" && row.bracket === "set"
  ));
  setVisual.raw_value = "Forged Set";
  setVisual.normalized_value = "Forged Set";
  const forgedRecord = await read(forged);
  assert.throws(() => composeResolutionView(forgedRecord), rejectsBrokenPacket,
    "ordinary v3 readback rejects a forged visual Set transition");

  const normalizedTamper = structuredClone(rows.evidence);
  normalizedTamper.find((row) => (
    row.modality === "WHOLE_CARD_VISUAL" && row.bracket === "set"
  )).normalized_value = "Forged Normalized Set";
  const normalizedTamperRecord = await read(normalizedTamper);
  assert.throws(() => composeResolutionView(normalizedTamperRecord), rejectsBrokenPacket,
    "ordinary v3 readback rejects raw/normalized relation evidence drift");

  const emptyVisual = structuredClone(rows.evidence);
  emptyVisual.find((row) => (
    row.modality === "WHOLE_CARD_VISUAL" && row.bracket === "set"
  )).raw_value = "";
  emptyVisual.find((row) => (
    row.modality === "WHOLE_CARD_VISUAL" && row.bracket === "set"
  )).normalized_value = "";
  const emptyVisualRecord = await read(emptyVisual);
  assert.throws(() => composeResolutionView(emptyVisualRecord), rejectsBrokenPacket,
    "ordinary v3 readback rejects an impossible empty visual relation row");

  const crossSession = structuredClone(rows.evidence);
  crossSession.find((row) => (
    row.modality === "WHOLE_CARD_VISUAL" && row.bracket === "set"
  )).source_ref = { images: "different-session" };
  const crossSessionRecord = await read(crossSession);
  assert.throws(() => composeResolutionView(crossSessionRecord), rejectsBrokenPacket,
    "ordinary v3 readback rejects cross-session visual relation evidence");
}

// --- the view is a pure read -------------------------------------------------
{
  const view = await handleResolutionViewRequest({ tenantId: "t1", assetId: "asset-1", dependencies: deps });
  assert.ok(view.brackets.length >= 13);
  assert.equal(view.composer.recomposed_matches_stored, true);
  assert.equal(view.composer.trace_reliable, true);
  assert.ok(view.composer.composer_version, "the version the trace was produced under travels with it");
  assert.equal(view.composer.composer_version, THIN_COMPOSER_VERSION);
  assert.equal(view.composer.marketplace_profile_version,
    LYNCA_STANDARD_PROFILE_VERSION_V2);
  assert.equal(view.brackets.find((entry) => entry.bracket === "search_optimization").value,
    "RC, Dodgers", "the captured writer uses the registered CNL search projection");
  assert.deepEqual(
    view.brackets.find((entry) => entry.bracket === "search_optimization").canonical_fields,
    ["components", "search_optimization", "team"]
  );
  assert.deepEqual(view.owner_execution_receipt, {
    version: CSM_OWNER_EXECUTION_RECEIPT_VERSION,
    sha256: OWNER_RECEIPT_SHA256
  });
  assert.doesNotMatch(JSON.stringify(view.owner_execution_receipt), /must-not-leave-the-server/,
    "the resolution route exposes only the allow-listed receipt version and hash");
}

// Historical v2 rows exercise the replay reader, not only the flat-record
// compatibility shim. This fingerprint is the complete de55 HTTP view.
{
  const replayFields = parseCanonicalFields(JSON.parse(payload)).fields;
  const replayComposed = composeFromCanonicalFields(replayFields);
  const replayRows = buildCsmStageRows({
    tenantId: "t1",
    recognitionSessionId: "sess-replay",
    fields: replayFields,
    composed: replayComposed,
    title: replayComposed.title,
    createdAt: "2026-08-11T00:00:00.000Z",
    contractVersion: "csm-stage-shadow-v2"
  });
  const replayRecord = {
    asset_id: "asset-replay",
    recognition_session_id: "sess-replay",
    resolution_id: replayRows.resolution.id,
    output_id: replayRows.output.id,
    output_title: replayRows.output.title,
    resolver_version: replayRows.resolution.resolver_version,
    owner_execution_receipt: {
      version: CSM_OWNER_EXECUTION_RECEIPT_VERSION,
      sha256: OWNER_RECEIPT_SHA256
    },
    replay_rows: replayRows
  };
  const publicView = await handleResolutionViewRequest({
    tenantId: "t1",
    assetId: replayRecord.asset_id,
    dependencies: { readRecord: async () => replayRecord }
  });
  assert.equal(sha256Json(publicView), DE55_LEGACY_REPLAY_VIEW_SHA256,
    "stored v2 replay rows must retain the complete de55 public projection");
}

// --- the safe receipt is recomputed from the durable session JSON ------------
{
  const rawOwner = Object.fromEntries(
    CSM_OWNER_EXECUTION_RECEIPT_KEYS.map((key) => [key, null])
  );
  Object.assign(rawOwner, {
    provider: "openai",
    model: "gpt-5.6-luna",
    provider_response_id: "resp_private_readback",
    provider_request_id: "req_private_readback",
    provider_transport_retry_receipt: {
      schema_version: "luna-definitive-502-transport-retry-receipt-v1",
      receipt_sha256: "c".repeat(64)
    },
    composer: "thin-marketplace-composer-v2",
    resolver: "thin-path-observation-only-v1"
  });
  const storedOwner = sealCsmOwnerExecutionReceipt(rawOwner);
  const requested = [];
  const dbFetch = async (rawUrl) => {
    const url = new URL(rawUrl);
    requested.push(url);
    if (url.pathname.endsWith("/v4_recognition_sessions")) {
      return new Response(JSON.stringify([{
        id: "session-db", asset_id: "asset-db", created_at: "2026-08-09T00:00:00Z",
        csm_owner_versions: storedOwner
      }]), { status: 200 });
    }
    if (url.pathname.endsWith("/csm_marketplace_outputs")) {
      return new Response(JSON.stringify([{
        id: "output-db", tenant_id: "tenant-db", recognition_session_id: "session-db",
        resolution_id: "resolution-db", structured_output: {}, title: "stored-title",
        composer_version: "thin-marketplace-composer-v2",
        marketplace: "EBAY", marketplace_profile_version: "ebay-profile-v1",
        contract_version: "csm-stage-shadow-v2", created_at: "2026-08-09T00:00:00Z"
      }]), { status: 200 });
    }
    if (url.pathname.endsWith("/csm_identity_resolutions")) {
      return new Response(JSON.stringify([{
        id: "resolution-db", resolver_version: "thin-path-observation-only-v1",
        conflict_policy_version: "none-single-observation-v1",
        registry_release_id: "registry_thin_20260801_v1",
        grammar: "NON_TCG", contract_version: "csm-stage-shadow-v2", revision: 1
      }]), { status: 200 });
    }
    if (url.pathname.endsWith("/csm_resolved_brackets")) {
      return new Response("[]", { status: 200 });
    }
    if ([
      "/csm_evidence_observations",
      "/csm_bracket_candidates",
      "/csm_candidate_evidence_links"
    ].some((suffix) => url.pathname.endsWith(suffix))) {
      return new Response("[]", { status: 200 });
    }
    return new Response("[]", { status: 404 });
  };
  const durable = await readCsmResolutionRecord({
    tenantId: "tenant-db",
    assetId: "asset-db",
    env: {
      SUPABASE_URL: "https://example.supabase.co",
      SUPABASE_SERVICE_ROLE_KEY: "service-role"
    },
    fetchImpl: dbFetch
  });
  assert.match(
    requested.find((url) => url.pathname.endsWith("/v4_recognition_sessions"))
      .searchParams.get("select"),
    /csm_owner_versions/,
    "the resolution read must fetch the receipt from the durable session row"
  );
  assert.deepEqual(durable.owner_execution_receipt, {
    version: CSM_OWNER_EXECUTION_RECEIPT_VERSION,
    sha256: storedOwner.owner_execution_receipt_sha256
  });
  assert.equal(durable.registry_release_id, "registry_thin_20260801_v1");
  assert.equal(durable.conflict_policy_version, "none-single-observation-v1");
  assert.equal(durable.marketplace_profile_version, "ebay-profile-v1");
  assert.ok(requested.some((url) => url.pathname.endsWith("/csm_evidence_observations")),
    "every replay read loads its packet rows before choosing a projector");
  assert.ok(!requested.some((url) => url.pathname.endsWith("/csm_registry_releases")),
    "a baseline read must not pay for an external Registry query");
  assert.doesNotMatch(JSON.stringify(durable.owner_execution_receipt),
    /resp_private_readback|req_private_readback|stored-title/,
    "raw provider ids and title must not enter the public receipt projection");

  const tamperedOwner = { ...storedOwner, output_tokens: 1 };
  await assert.rejects(
    () => readCsmResolutionRecord({
      tenantId: "tenant-db",
      assetId: "asset-db",
      env: {
        SUPABASE_URL: "https://example.supabase.co",
        SUPABASE_SERVICE_ROLE_KEY: "service-role"
      },
      fetchImpl: async (rawUrl) => {
        const url = new URL(rawUrl);
        if (url.pathname.endsWith("/v4_recognition_sessions")) {
          return new Response(JSON.stringify([{
            id: "session-db", asset_id: "asset-db", csm_owner_versions: tamperedOwner
          }]), { status: 200 });
        }
        return dbFetch(rawUrl);
      }
    }),
    /csm_owner_execution_receipt_invalid/,
    "the GET path must fail closed when durable owner bytes no longer match the saved hash"
  );

  const nestedRetryTamper = structuredClone(storedOwner);
  nestedRetryTamper.provider_transport_retry_receipt.receipt_sha256 = "d".repeat(64);
  await assert.rejects(
    () => readCsmResolutionRecord({
      tenantId: "tenant-db",
      assetId: "asset-db",
      env: {
        SUPABASE_URL: "https://example.supabase.co",
        SUPABASE_SERVICE_ROLE_KEY: "service-role"
      },
      fetchImpl: async (rawUrl) => {
        const url = new URL(rawUrl);
        if (url.pathname.endsWith("/v4_recognition_sessions")) {
          return new Response(JSON.stringify([{
            id: "session-db", asset_id: "asset-db", created_at: "2026-08-09T00:00:00Z",
            csm_owner_versions: nestedRetryTamper
          }]), { status: 200 });
        }
        if (url.pathname.endsWith("/csm_marketplace_outputs")) {
          return new Response(JSON.stringify([{
            id: "output-db", tenant_id: "tenant-db", recognition_session_id: "session-db",
            resolution_id: "resolution-db", structured_output: {}, title: "stored-title",
            composer_version: "thin-marketplace-composer-v2",
            marketplace: "EBAY", marketplace_profile_version: "ebay-profile-v1",
            contract_version: "csm-stage-shadow-v2", created_at: "2026-08-09T00:00:00Z"
          }]), { status: 200 });
        }
        if (url.pathname.endsWith("/csm_identity_resolutions")) return new Response("[]", { status: 200 });
        if (url.pathname.endsWith("/csm_resolved_brackets")) return new Response("[]", { status: 200 });
        return new Response("[]", { status: 200 });
      }
    }),
    /csm_owner_execution_receipt_invalid/,
    "zero-call resolution readback must reject nested transport-retry receipt drift"
  );
}

// --- APPLIED external identity is visible only through a safe DB projection -
{
  const releases = EXTERNAL_IDENTITY_REPLAY_COMPATIBILITY_REGISTRY.releases;
  const v1 = releases.registry_thin_external_identity_high_risers_v1;
  const v2 = releases.registry_thin_external_identity_high_risers_v2;
  const v3 = releases.registry_thin_external_identity_high_risers_v3;
  const registryVersions = {
    registry_thin_external_identity_high_risers_v1:
      "thin-path-external-identity-high-risers-v1",
    registry_thin_external_identity_high_risers_v2:
      "thin-path-external-identity-high-risers-v2",
    registry_thin_external_identity_high_risers_v3:
      "thin-path-external-identity-high-risers-v3"
  };
  const tcdbFact = "57742a7673c905bd6db1d7e3322801fb78a8709b335aad9738b22adb855e4c1d";
  const psaFact = "83fd1914ef27e6c1191a64b830a83423eb7d185cdbbb3e22c6a9f1b7df86f392";
  const beckettFact = "f13da45a28bc73b8abad4980493a9eee369435022342231b77a3bed8b1a3653c";
  const originalSetSha256 =
    "61ee1d99b10690cf5877e9b5f08b53ba98051a3961d0a9e5c04f9e8e130db159";
  const sources = {
    tcdb: {
      source_id: "tcdb.set.2551",
      url: "https://www.tcdb.com/Checklist.cfm/sid/2551/1996-97-Stadium-Club---High-Risers",
      retrieved_at: "2026-08-10", fact_sha256: tcdbFact, raw_payload: "must-not-leave-db"
    },
    psa: {
      source_id: "psa.set-registry.25618",
      url: "https://www.psacard.com/psasetregistry/basketball/company-sets/1996-97-stadium-club-high-risers-members-only/composition/25618",
      retrieved_at: "2026-08-10", fact_sha256: psaFact
    },
    beckett: {
      source_id: "beckett.item.3117708",
      url: "https://www.beckett.com/basketball/1996-97/stadium-club-high-risers/hr14-michael-jordan-3117708",
      retrieved_at: "2026-08-10", fact_sha256: beckettFact
    },
    wrongHost: {
      source_id: "tcdb.set.evil", url: "https://attacker.example/steal",
      retrieved_at: "2026-08-10", fact_sha256: "7".repeat(64)
    },
    wrongScheme: {
      source_id: "psa.set-registry.http", url: "http://www.psacard.com/not-https",
      retrieved_at: "2026-08-10", fact_sha256: "8".repeat(64)
    }
  };
  const baseDecisions = {
    year: {
      action: "CORROBORATE", observed_value: "1996-97", canonical_value: "1996-97",
      source_ids: ["tcdb.set.2551", "psa.set-registry.25618", "beckett.item.3117708"]
    },
    manufacturer: {
      action: "CORROBORATE", observed_value: "Topps", canonical_value: "Topps",
      source_ids: ["beckett.item.3117708"]
    },
    product: {
      action: "CORROBORATE", observed_value: "Stadium Club", canonical_value: "Stadium Club",
      source_ids: ["tcdb.set.2551", "psa.set-registry.25618", "beckett.item.3117708"]
    },
    set: {
      action: "CORROBORATE", observed_value: "High Risers", canonical_value: "High Risers",
      source_ids: ["tcdb.set.2551", "psa.set-registry.25618", "beckett.item.3117708"]
    },
    subjects: {
      action: "CORROBORATE", observed_value: ["Michael Jordan"], canonical_value: ["Michael Jordan"],
      source_ids: ["tcdb.set.2551", "psa.set-registry.25618", "beckett.item.3117708"]
    },
    card_number: {
      action: "CORROBORATE", observed_value: "HR14", canonical_value: "HR14",
      source_ids: ["tcdb.set.2551", "psa.set-registry.25618", "beckett.item.3117708"]
    },
    team: {
      action: "FILL", observed_value: "", canonical_value: "Chicago Bulls",
      source_ids: ["tcdb.set.2551", "beckett.item.3117708"]
    }
  };
  const storedReceipt = (descriptor, {
    matchMode = "VERIFIED_ORIGINAL_SET", fieldDecisions = baseDecisions
  } = {}) => ({
    ...descriptor.receipt,
    record_id: "tcdb-2551-hr14",
    match_mode: matchMode,
    ...(matchMode === "VERIFIED_ORIGINAL_SET" ? {
      original_set_sha256: originalSetSha256
    } : {}),
    field_decisions: fieldDecisions
  });
  const sourceRef = (stored, field, supportedSources) => ({
    support_type: "EXACT_EXTERNAL_IDENTITY",
    field,
    decision: stored.field_decisions[field].action,
    pack_id: stored.pack_id,
    pack_version: stored.pack_version,
    pack_sha256: stored.pack_sha256,
    index_id: stored.index_id,
    index_version: stored.index_version,
    index_sha256: stored.index_sha256,
    record_id: stored.record_id,
    registry_release_id: stored.registry_release_id,
    resolution_contract_sha256: stored.resolution_contract_sha256,
    match_mode: stored.match_mode,
    ...(stored.original_set_sha256 ? {
      original_set_sha256: stored.original_set_sha256
    } : {}),
    sources: supportedSources,
    raw_registry_payload: { api_key: "must-not-leave-db" }
  });
  const registryRow = (descriptor) => ({
    id: descriptor.receipt.registry_release_id,
    registry_version: registryVersions[descriptor.receipt.registry_release_id],
    content_sha256: descriptor.receipt.pack_sha256,
    sem_standard_version: "linear-cos-10-23-v25",
    registry_payload: {
      mode: "post_observation_exact_external_identity",
      external_catalog: true,
      pack_id: descriptor.receipt.pack_id,
      pack_version: descriptor.receipt.pack_version,
      index_id: descriptor.receipt.index_id,
      pack_sha256: descriptor.receipt.pack_sha256,
      index_sha256: descriptor.receipt.index_sha256,
      resolution_contract_sha256: descriptor.receipt.resolution_contract_sha256,
      provider_calls_added: 0
    }
  });
  const sourceById = new Map([sources.tcdb, sources.psa, sources.beckett]
    .map((source) => [source.source_id, source]));
  const bracketForField = (field) => ({
    subjects: "subject",
    team: "search_optimization"
  })[field] || field;
  const bracketValue = (field, value) => (
    field === "team" ? (String(value || "").trim() ? [value] : []) : value
  );
  const evidenceFor = (stored) => {
    const registry = Object.entries(stored.field_decisions).map(([field, decision]) => ({
      bracket: bracketForField(field),
      raw_value: decision.canonical_value,
      normalized_value: bracketValue(field, decision.canonical_value),
      modality: "REGISTRY",
      observation_confidence: 1,
      normalization_version: stored.index_version,
      normalization_outcome: "KEPT",
      normalization_reason_code: `EXTERNAL_IDENTITY_${decision.action}`,
      source_ref: sourceRef(
        stored,
        field,
        decision.source_ids.map((sourceId) => sourceById.get(sourceId)).filter(Boolean)
      )
    }));
    const visual = Object.entries(stored.field_decisions)
      .filter(([field, decision]) => (
        field === "subjects"
          ? decision.observed_value.length > 0
          : String(decision.observed_value || "").trim()
      ))
      .map(([field, decision]) => ({
        bracket: bracketForField(field),
        raw_value: bracketValue(field, decision.observed_value),
        normalized_value: bracketValue(field, decision.observed_value),
        modality: "WHOLE_CARD_VISUAL",
        observation_confidence: 0.8,
        normalization_version: SEM_STANDARD_VERSION,
        normalization_outcome: "KEPT",
        normalization_reason_code: "DIRECT_OBSERVATION",
        source_ref: { images: "external-session" }
      }));
    return [...registry, ...visual];
  };
  const resolvedFor = (stored) => Object.entries(stored.field_decisions)
    .map(([field, decision]) => ({
      bracket: bracketForField(field),
      selected_kind: "VALUE",
      canonical_value: bracketValue(field, decision.canonical_value)
    }));
  const completeRowsFor = (descriptor, stored, {
    contractVersion = "csm-stage-shadow-v2"
  } = {}) => {
    const observedFields = parseCanonicalFields({
      year: stored.field_decisions.year.observed_value,
      manufacturer: stored.field_decisions.manufacturer.observed_value,
      product: stored.field_decisions.product.observed_value,
      set: stored.field_decisions.set.observed_value,
      subjects: stored.field_decisions.subjects.observed_value,
      team: stored.field_decisions.team.observed_value,
      card_name: "",
      release_variant: "",
      surface_color: "",
      parallel_family: "",
      parallel_exact: "",
      descriptive_rarity: "",
      card_number: stored.field_decisions.card_number.observed_value,
      serial: "",
      attributes: [],
      grading_info: null,
      grammar: "standard",
      lot_count: "",
      language: "",
      unreadable: [],
      low_confidence: []
    }).fields;
    const fields = {
      ...observedFields,
      ...Object.fromEntries(Object.entries(stored.field_decisions).map(
        ([field, decision]) => [field, decision.canonical_value]
      ))
    };
    const support = {
      ...stored,
      status: "APPLIED",
      source_ids: EXTERNAL_IDENTITY_SUPPORT_PACK.sources.map((source) => source.source_id),
      sources: EXTERNAL_IDENTITY_SUPPORT_PACK.sources,
      source_field_map: Object.fromEntries(Object.entries(stored.field_decisions).map(
        ([field, decision]) => [field, decision.source_ids]
      )),
      supported_fields: Object.keys(stored.field_decisions),
      corrected_fields: Object.entries(stored.field_decisions)
        .filter(([, decision]) => decision.action === "CORRECT_CONFLICT")
        .map(([field]) => field)
    };
    const composed = composeCanonicalFieldsForStoredOutput(fields, {
      marketplace: "EBAY",
      ...descriptor.output,
      contract_version: contractVersion
    });
    const receipts = contractVersion === "csm-stage-shadow-v3"
      ? noSearchDurableReceipts(fields)
      : { founderBetaWebReceipt: null, setCardNameRelationReceipt: null };
    return buildCsmStageRows({
      tenantId: "tenant-db",
      recognitionSessionId: "external-session",
      fields,
      observedFields,
      externalIdentitySupport: support,
      ...receipts,
      composed,
      title: composed.title,
      registryReleaseId: descriptor.receipt.registry_release_id,
      createdAt: "2026-08-10T00:00:00Z",
      contractVersion
    });
  };
  const env = {
    SUPABASE_URL: "https://example.supabase.co",
    SUPABASE_SERVICE_ROLE_KEY: "service-role"
  };
  const readExternal = async ({
    descriptor, stored = storedReceipt(descriptor), outputOverrides = {},
    resolutionOverrides = {}, registryOverrides = {}, evidenceRows = null,
    resolvedRows = null, contractVersion = "csm-stage-shadow-v2"
  }) => {
    let completeRows;
    try {
      completeRows = completeRowsFor(descriptor, stored, { contractVersion });
    } catch {
      completeRows = completeRowsFor(
        descriptor, storedReceipt(descriptor), { contractVersion }
      );
    }
    completeRows.output = {
      ...completeRows.output,
      structured_output: {
        ...completeRows.output.structured_output,
        external_identity_support: stored
      }
    };
    evidenceRows ||= completeRows.evidence;
    resolvedRows ||= completeRows.resolved;
    const requested = [];
    const fetchImpl = async (rawUrl) => {
      const url = new URL(rawUrl);
      requested.push(url);
      if (url.pathname.endsWith("/v4_recognition_sessions")) {
        return new Response(JSON.stringify([{
          id: "external-session", asset_id: "external-asset", created_at: "2026-08-10T00:00:00Z",
          csm_owner_versions: null,
          ...completeRows.session_hashes
        }]), { status: 200 });
      }
      if (url.pathname.endsWith("/csm_marketplace_outputs")) {
        return new Response(JSON.stringify([{
          ...completeRows.output,
          ...outputOverrides
        }]), { status: 200 });
      }
      if (url.pathname.endsWith("/csm_identity_resolutions")) {
        return new Response(JSON.stringify([{
          ...completeRows.resolution,
          ...resolutionOverrides
        }]), { status: 200 });
      }
      if (url.pathname.endsWith("/csm_resolved_brackets")) {
        return new Response(JSON.stringify(resolvedRows), { status: 200 });
      }
      if (url.pathname.endsWith("/csm_registry_releases")) {
        return new Response(JSON.stringify([{
          ...registryRow(descriptor), ...registryOverrides
        }]), { status: 200 });
      }
      if (url.pathname.endsWith("/csm_evidence_observations")) {
        return new Response(JSON.stringify(evidenceRows), { status: 200 });
      }
      if (url.pathname.endsWith("/csm_bracket_candidates")) {
        return new Response(JSON.stringify(completeRows.candidates), { status: 200 });
      }
      if (url.pathname.endsWith("/csm_candidate_evidence_links")) {
        return new Response(JSON.stringify(completeRows.links), { status: 200 });
      }
      return new Response("[]", { status: 404 });
    };
    const value = await readCsmResolutionRecord({
      tenantId: "tenant-db", assetId: "external-asset", env, fetchImpl
    });
    return { value, requested };
  };

  const storedExternal = storedReceipt(v1);
  const { value: durable, requested } = await readExternal({ descriptor: v1, stored: storedExternal });
  const support = durable.external_identity_support;
  assert.equal(durable.registry_release_id, v1.receipt.registry_release_id,
    "historical v1 receipts remain readable after v2 becomes active");
  assert.equal(support.status, "APPLIED");
  assert.equal(support.match_basis, "VERIFIED_ORIGINAL_SET");
  assert.equal(support.registry_release.id, v1.receipt.registry_release_id);
  assert.equal(support.registry_release.registry_version,
    "thin-path-external-identity-high-risers-v1");
  assert.equal(support.registry_release.content_sha256, v1.receipt.pack_sha256);
  assert.equal(support.resolution_contract_sha256, v1.receipt.resolution_contract_sha256);
  assert.equal(support.index.version, storedExternal.index_version);
  assert.deepEqual(support.supported_fields,
    ["year", "manufacturer", "product", "set", "subjects", "team", "card_number"]);
  assert.deepEqual(support.sources.map((source) => source.provider).sort(), ["Beckett", "PSA", "TCDB"]);
  assert.equal(support.sources.find((source) => source.provider === "TCDB").url,
    sources.tcdb.url,
    "the public source must be the exact source-versioned snapshot");
  assert.deepEqual(support.sources.find((source) => source.provider === "TCDB").fields,
    ["card_number", "product", "set", "subjects", "team", "year"]);
  assert.deepEqual(support.field_decisions.team, {
    action: "FILL", source_ids: ["beckett.item.3117708", "tcdb.set.2551"]
  });
  assert.equal(Object.prototype.hasOwnProperty.call(support, "original_set_sha256"), false,
    "the public match basis must not expose the private original-set digest");
  assert.doesNotMatch(JSON.stringify(support),
    /must-not-leave|raw_payload|canonical_value|observed_value|attacker\.example|not-https|api_key/,
    "raw Registry/evidence payload and rejected URLs must stop at the DB projection");

  const durableExternalView = await handleResolutionViewRequest({
    tenantId: "tenant-db", assetId: "external-asset",
    dependencies: { readRecord: async () => durable }
  });
  assert.equal(durableExternalView.composer.composer_version, v1.output.composer_version);
  assert.equal(Object.hasOwn(
    durableExternalView.composer,
    "marketplace_profile_version"
  ), false, "published external v1 keeps the de55 public key set");
  assert.ok(durableExternalView.brackets.every(
    (entry) => !Object.hasOwn(entry, "canonical_fields")
  ), "published external v1 keeps the de55 bracket shape");
  assert.equal(durableExternalView.composer.trace_reliable, true);
  assert.equal(durableExternalView.external_identity_support.registry_release.id,
    v1.receipt.registry_release_id);

  const withoutVerifiedReceipt = structuredClone(durable);
  delete withoutVerifiedReceipt.external_identity_support;
  assert.throws(
    () => composeResolutionView(withoutVerifiedReceipt),
    (error) => error?.statusCode === 409
      && error?.message === "csm_resolution_external_identity_receipt_invalid",
    "an external executable pair cannot be explained without its verified receipt"
  );
  const malformedVerifiedReceipt = structuredClone(durable);
  malformedVerifiedReceipt.external_identity_support.sources = [];
  assert.throws(
    () => composeResolutionView(malformedVerifiedReceipt),
    (error) => error?.statusCode === 409
      && error?.message === "csm_resolution_external_identity_receipt_invalid",
    "an invalid public external receipt must fail the read model closed"
  );

  const evidenceRead = requested.find((url) => url.pathname.endsWith("/csm_evidence_observations"));
  assert.equal(evidenceRead.searchParams.get("select"),
    "bracket,raw_value,normalized_value,modality,source_ref,observation_confidence,normalization_version,normalization_outcome,normalization_reason_code");
  assert.equal(evidenceRead.searchParams.has("modality"), false,
    "the private packet read must not hide a drifted exact-support modality");
  assert.equal(evidenceRead.searchParams.get("recognition_session_id"), "eq.external-session");
  assert.equal(evidenceRead.searchParams.get("tenant_id"), "eq.tenant-db");
  const resolutionRead = requested.find((url) => url.pathname.endsWith("/csm_identity_resolutions"));
  assert.match(resolutionRead.searchParams.get("select"), /registry_release_id/);
  assert.match(resolutionRead.searchParams.get("select"), /conflict_policy_version/);

  const view = await handleResolutionViewRequest({
    tenantId: "tenant-db", assetId: "asset-1",
    dependencies: { readRecord: async () => ({
      ...record,
      resolver_version: support.resolver_version,
      external_identity_support: {
        ...support,
        raw_registry_payload: { secret: "must-not-leave-view" }
      }
    }) }
  });
  assert.equal(view.external_identity_support.sources.length, 3);
  assert.equal(view.external_identity_support.match_basis, "VERIFIED_ORIGINAL_SET");
  assert.equal(view.summary.external_supported_fields, 7);
  for (const bracket of view.brackets.filter((entry) => ["team", "card_number"].includes(entry.canonical_field))) {
    assert.ok(bracket.rationale_codes.includes("EXACT_EXTERNAL_IDENTITY_SUPPORT"));
    assert.equal(bracket.semantic_confidence, "VERIFIED_EXTERNAL");
    assert.equal(bracket.alternates_unavailable_reason, "EXACT_EXTERNAL_IDENTITY_RESOLUTION");
  }
  assert.doesNotMatch(JSON.stringify(view), /must-not-leave-view|raw_registry_payload/);
  assert.deepEqual(publicExternalIdentitySupport({ ...support, sources: [sources.wrongHost] }), null,
    "an injected non-allowlisted source cannot create a public APPLIED receipt");
  assert.deepEqual(publicExternalIdentitySupport({ ...support, match_basis: "UNKNOWN" }), null,
    "an unknown match basis cannot cross the public receipt boundary");
  assert.deepEqual(publicExternalIdentitySupport({ ...support, resolver_version: "forged" }), null,
    "an injected public receipt cannot replace the append-only release tuple");
  assert.deepEqual(publicExternalIdentitySupport({
    ...support,
    sources: support.sources.map((source, index) => index === 0 ? {
      ...source,
      url: "https://www.tcdb.com/arbitrary-but-same-host",
      retrieved_at: "2099-01-01",
      fact_sha256: "f".repeat(64)
    } : source)
  }), null, "same-host source drift is not source-versioned evidence");
  assert.deepEqual(publicExternalIdentitySupport({
    ...support,
    field_decisions: {
      ...support.field_decisions,
      card_number: { ...support.field_decisions.card_number, action: "CORRECT_CONFLICT" }
    }
  }), null, "only year/set may carry a public conflict-correction receipt");
  const whitespaceDecisionSource = structuredClone(support);
  for (const decision of Object.values(whitespaceDecisionSource.field_decisions)) {
    decision.source_ids = decision.source_ids.map((sourceId) => (
      sourceId === "tcdb.set.2551" ? " tcdb.set.2551 " : sourceId
    ));
  }
  whitespaceDecisionSource.sources = whitespaceDecisionSource.sources.map((source) => (
    source.source_id === "tcdb.set.2551" ? { ...source, fields: [] } : source
  ));
  assert.deepEqual(publicExternalIdentitySupport(whitespaceDecisionSource), null,
    "whitespace source ids cannot erase their public field coverage");

  const { value: mismatchedBasis } = await readExternal({
    descriptor: v1,
    stored: storedExternal,
    evidenceRows: [{
      source_ref: {
        ...sourceRef(storedExternal, "card_number", [sources.tcdb]),
        original_set_sha256: "a".repeat(64)
      }
    }]
  });
  assert.equal(mismatchedBasis.external_identity_support, undefined,
    "public match basis requires the durable Registry evidence to bind the same private set digest");
  const { value: missingFieldEvidence } = await readExternal({
    descriptor: v1,
    stored: storedExternal,
    evidenceRows: [{
      source_ref: sourceRef(storedExternal, "card_number", [sources.tcdb])
    }]
  });
  assert.equal(missingFieldEvidence.external_identity_support, undefined,
    "a source observed for one field cannot launder a second field without its own durable evidence");

  const duplicateRegistryEvidence = evidenceFor(storedExternal);
  duplicateRegistryEvidence.push(structuredClone(
    duplicateRegistryEvidence.find((row) => (
      row.modality === "REGISTRY" && row.source_ref.field === "year"
    ))
  ));
  const { value: duplicated } = await readExternal({
    descriptor: v1, stored: storedExternal, evidenceRows: duplicateRegistryEvidence
  });
  assert.equal(duplicated.external_identity_support, undefined,
    "a duplicate durable Registry field must fail the whole support packet closed");

  const unexpectedRegistryEvidence = evidenceFor(storedExternal);
  const unexpected = structuredClone(unexpectedRegistryEvidence.find((row) => (
    row.modality === "REGISTRY" && row.source_ref.field === "year"
  )));
  unexpected.bracket = "serial";
  unexpected.source_ref.field = "serial";
  unexpectedRegistryEvidence.push(unexpected);
  const { value: withUnexpected } = await readExternal({
    descriptor: v1, stored: storedExternal, evidenceRows: unexpectedRegistryEvidence
  });
  assert.equal(withUnexpected.external_identity_support, undefined,
    "an unexpected durable Registry field must fail the whole support packet closed");

  const wrongModalityEvidence = evidenceFor(storedExternal);
  wrongModalityEvidence.find((row) => (
    row.modality === "REGISTRY" && row.source_ref.field === "year"
  )).modality = "CARD_TEXT_OCR";
  const { value: wrongModality } = await readExternal({
    descriptor: v1, stored: storedExternal, evidenceRows: wrongModalityEvidence
  });
  assert.equal(wrongModality.external_identity_support, undefined,
    "an exact-support row with a forged modality must remain visible and fail closed");

  const exactlyLimitedEvidence = evidenceFor(storedExternal);
  while (exactlyLimitedEvidence.length < 100) {
    exactlyLimitedEvidence.push({
      bracket: "serial",
      raw_value: "irrelevant",
      normalized_value: "irrelevant",
      modality: "WHOLE_CARD_VISUAL",
      source_ref: { images: "external-session" }
    });
  }
  await assert.rejects(() => readExternal({
    descriptor: v1, stored: storedExternal, evidenceRows: exactlyLimitedEvidence
  }), /csm_replay_readback_truncated/,
  "a response exactly at the query limit has no completeness proof and must fail closed");

  for (const [name, sourceOverride] of [
    ["path", { url: "https://www.beckett.com/basketball/changed-path" }],
    ["fact hash", { fact_sha256: "a".repeat(64) }],
    ["retrieval date", { retrieved_at: "2026-08-09" }]
  ]) {
    const evidenceRows = evidenceFor(storedExternal).map((row) => (
      row.source_ref.field === "manufacturer"
        ? {
            source_ref: sourceRef(storedExternal, "manufacturer", [{
              ...sources.beckett,
              ...sourceOverride
            }])
          }
        : row
    ));
    const { value } = await readExternal({ descriptor: v1, stored: storedExternal, evidenceRows });
    assert.equal(value.external_identity_support, undefined,
      `a legal source id with a changed ${name} must fail the source-versioned snapshot`);
  }

  const v2Decisions = {
    ...baseDecisions,
    year: {
      action: "CORRECT_CONFLICT", observed_value: "1994-95", canonical_value: "1996-97",
      source_ids: ["tcdb.set.2551", "psa.set-registry.25618", "beckett.item.3117708"]
    },
    set: {
      action: "CORRECT_CONFLICT", observed_value: "Hardwood Heroes", canonical_value: "High Risers",
      source_ids: ["tcdb.set.2551", "psa.set-registry.25618", "beckett.item.3117708"]
    }
  };
  const v2Stored = storedReceipt(v2, { fieldDecisions: v2Decisions });
  const { value: v2Durable } = await readExternal({ descriptor: v2, stored: v2Stored });
  assert.equal(v2Durable.external_identity_support.registry_release.id,
    v2.receipt.registry_release_id);
  assert.equal(v2Durable.external_identity_support.registry_release.registry_version,
    "thin-path-external-identity-high-risers-v2");
  assert.equal(v2Durable.external_identity_support.field_decisions.year.action, "CORRECT_CONFLICT");
  assert.equal(v2Durable.external_identity_support.field_decisions.set.action, "CORRECT_CONFLICT");
  assert.equal(v2Durable.external_identity_support.composer_version, v2.output.composer_version);
  assert.ok(Array.isArray(v2Durable.replay_rows.evidence),
    "the private external evidence needed by relation replay stays in the server-side bundle");
  const missingPrivateReceipt = structuredClone(v2Durable);
  delete missingPrivateReceipt.replay_rows.output.structured_output.external_identity_support;
  delete missingPrivateReceipt.external_identity_support;
  assert.throws(() => composeResolutionView(missingPrivateReceipt), (error) => (
    error?.statusCode === 409
      && error?.message === "csm_resolution_replay_integrity_invalid"
  ), "an external output without its private receipt must fail readback closed");

  const v3Decisions = {
    ...baseDecisions,
    year: {
      action: "CORRECT_CONFLICT", observed_value: "1992", canonical_value: "1996-97",
      source_ids: ["tcdb.set.2551", "psa.set-registry.25618", "beckett.item.3117708"]
    },
    product: {
      action: "CORRECT_CONFLICT", observed_value: "Stadium Club Basketball",
      canonical_value: "Stadium Club",
      source_ids: ["tcdb.set.2551", "psa.set-registry.25618", "beckett.item.3117708"]
    },
    set: {
      action: "CORRECT_CONFLICT", observed_value: "High Flyers", canonical_value: "High Risers",
      source_ids: ["tcdb.set.2551", "psa.set-registry.25618", "beckett.item.3117708"]
    }
  };
  const v3Stored = storedReceipt(v3, { fieldDecisions: v3Decisions });
  const { value: v3Durable } = await readExternal({
    descriptor: v3,
    stored: v3Stored,
    contractVersion: "csm-stage-shadow-v3"
  });
  assert.equal(v3Durable.external_identity_support.registry_release.id,
    v3.receipt.registry_release_id);
  assert.equal(v3Durable.external_identity_support.registry_release.registry_version,
    "thin-path-external-identity-high-risers-v3");
  assert.deepEqual(Object.fromEntries(["product", "year", "set"].map((field) => [
    field, v3Durable.external_identity_support.field_decisions[field].action
  ])), {
    product: "CORRECT_CONFLICT", year: "CORRECT_CONFLICT", set: "CORRECT_CONFLICT"
  });
  assert.deepEqual(v3.output, v2.output,
    "the forward release intentionally reuses the byte-identical output implementation");
  const durableExternalV3View = await handleResolutionViewRequest({
    tenantId: "tenant-db", assetId: "external-asset-v3",
    dependencies: { readRecord: async () => v3Durable }
  });
  assert.equal(durableExternalV3View.external_identity_support.registry_release.id,
    v3.receipt.registry_release_id,
  "same-output releases must be selected by their persisted receipt, not first tuple match");

  for (const [recordWithRows, substitutedSupport] of [
    [v2Durable, v3Durable.external_identity_support],
    [v3Durable, v2Durable.external_identity_support]
  ]) {
    assert.throws(
      () => composeResolutionView({
        ...recordWithRows,
        external_identity_support: substitutedSupport
      }),
      (error) => error?.statusCode === 409
        && error?.message === "csm_resolution_external_identity_receipt_invalid",
      "a same-output receipt from another release cannot authorize stored rows"
    );
  }

  const { value: v3RelationDurable } = await readExternal({
    descriptor: v2,
    stored: v2Stored,
    contractVersion: "csm-stage-shadow-v3"
  });
  assert.doesNotThrow(() => composeResolutionView(v3RelationDurable),
    "a real v3 external partial read keeps enough private evidence to validate Set authority");

  const duplicateV3RegistryEvidence = structuredClone(v3RelationDurable);
  duplicateV3RegistryEvidence.replay_rows.evidence.push(structuredClone(
    duplicateV3RegistryEvidence.replay_rows.evidence.find((row) => (
      row.modality === "REGISTRY"
    ))
  ));
  assert.throws(() => composeResolutionView(duplicateV3RegistryEvidence), (error) => (
    error?.statusCode === 409
      && error?.message === "csm_resolution_replay_integrity_invalid"
  ), "Resolution View rejects duplicate external Registry authority evidence");

  const extraV3RegistryEvidence = structuredClone(v3RelationDurable);
  const extraRegistryRow = structuredClone(
    extraV3RegistryEvidence.replay_rows.evidence.find((row) => row.modality === "REGISTRY")
  );
  extraRegistryRow.bracket = "print_finish";
  extraRegistryRow.source_ref.field = "parallel_exact";
  extraV3RegistryEvidence.replay_rows.evidence.push(extraRegistryRow);
  assert.throws(() => composeResolutionView(extraV3RegistryEvidence), (error) => (
    error?.statusCode === 409
      && error?.message === "csm_resolution_replay_integrity_invalid"
  ), "Resolution View rejects extra external Registry authority evidence");

  const missingV3RelationEvidence = structuredClone(v3RelationDurable);
  delete missingV3RelationEvidence.replay_rows.evidence;
  assert.throws(() => composeResolutionView(missingV3RelationEvidence), (error) => (
    error?.statusCode === 409
      && error?.message === "csm_resolution_replay_integrity_invalid"
  ), "v3 external relation readback fails closed when private evidence is missing");
  const durableExternalV2View = await handleResolutionViewRequest({
    tenantId: "tenant-db", assetId: "external-asset-v2",
    dependencies: { readRecord: async () => v2Durable }
  });
  assert.equal(durableExternalV2View.composer.composer_version, v2.output.composer_version);
  assert.equal(Object.hasOwn(
    durableExternalV2View.composer,
    "marketplace_profile_version"
  ), false, "published external v2 keeps the de55 public key set");
  assert.ok(durableExternalV2View.brackets.every(
    (entry) => !Object.hasOwn(entry, "canonical_fields")
  ), "published external v2 keeps the de55 bracket shape");
  assert.equal(durableExternalV2View.composer.trace_reliable, true);
  assert.throws(
    () => composeResolutionView({
      ...durable,
      external_identity_support: v2Durable.external_identity_support
    }),
    (error) => error?.statusCode === 409
      && error?.message === "csm_resolution_external_identity_receipt_invalid",
    "a valid receipt for another external release cannot authorize this output pair"
  );

  const forgedObservedStored = structuredClone(v2Stored);
  forgedObservedStored.field_decisions.year.observed_value = "1988-89";
  const { value: forgedObserved } = await readExternal({
    descriptor: v2,
    stored: forgedObservedStored,
    evidenceRows: evidenceFor(v2Stored),
    resolvedRows: resolvedFor(v2Stored)
  });
  assert.equal(forgedObserved.external_identity_support, undefined,
    "a re-sealed observed decision must remain bound to durable WHOLE_CARD_VISUAL values");

  const hr1SourceIds = {
    year: ["tcdb.set.2551", "psa.set-registry.25618"],
    product: ["tcdb.set.2551", "psa.set-registry.25618"],
    set: ["tcdb.set.2551", "psa.set-registry.25618"],
    subjects: ["tcdb.set.2551", "psa.set-registry.25618"],
    team: ["tcdb.set.2551"],
    card_number: ["tcdb.set.2551", "psa.set-registry.25618"]
  };
  const hr1Decisions = Object.fromEntries(Object.entries(hr1SourceIds).map(([field, sourceIds]) => [
    field,
    { action: "CORROBORATE", source_ids: sourceIds }
  ]));
  const hr1Public = {
    ...v2Durable.external_identity_support,
    record_id: "tcdb-2551-hr1",
    match_basis: "EXACT_FOUR_ANCHOR",
    supported_fields: Object.keys(hr1SourceIds),
    field_decisions: hr1Decisions,
    sources: v2Durable.external_identity_support.sources
      .filter((source) => ["tcdb.set.2551", "psa.set-registry.25618"].includes(source.source_id))
      .map((source) => ({
        ...source,
        fields: Object.entries(hr1SourceIds)
          .filter(([, sourceIds]) => sourceIds.includes(source.source_id))
          .map(([field]) => field)
      }))
  };
  assert.notDeepEqual(publicExternalIdentitySupport(hr1Public), null,
    "HR1 remains legal for its exact four-anchor public receipt");
  const fakeVerifiedHr1 = structuredClone(hr1Public);
  fakeVerifiedHr1.match_basis = "VERIFIED_ORIGINAL_SET";
  fakeVerifiedHr1.field_decisions.year.action = "CORRECT_CONFLICT";
  fakeVerifiedHr1.field_decisions.set.action = "CORRECT_CONFLICT";
  assert.deepEqual(publicExternalIdentitySupport(fakeVerifiedHr1), null,
    "VERIFIED_ORIGINAL_SET is frozen to the reviewed HR14 mapping");

  const unknownStored = {
    ...v2Stored,
    registry_release_id: "registry_unknown_external_identity_v99"
  };
  const { value: unknown, requested: unknownRequested } = await readExternal({
    descriptor: v2,
    stored: unknownStored,
    resolutionOverrides: { registry_release_id: unknownStored.registry_release_id }
  });
  assert.equal(unknown.external_identity_support, undefined);
  assert.throws(() => composeResolutionView(unknown), (error) => (
    error?.statusCode === 409
      && error?.message === "csm_resolution_replay_integrity_invalid"
  ), "an external output with an unknown private receipt must fail readback closed");
  assert.ok(!unknownRequested.some((url) => url.pathname.endsWith("/csm_registry_releases")),
    "unknown releases must fail closed before Registry projection");

  const tamperedReceipt = { ...v2Stored, pack_sha256: "a".repeat(64) };
  const { value: tampered, requested: tamperedRequested } = await readExternal({
    descriptor: v2, stored: tamperedReceipt
  });
  assert.equal(tampered.external_identity_support, undefined);
  assert.throws(() => composeResolutionView(tampered), (error) => (
    error?.statusCode === 409
      && error?.message === "csm_resolution_replay_integrity_invalid"
  ), "an external output with a tampered private receipt must fail readback closed");
  assert.ok(!tamperedRequested.some((url) => url.pathname.endsWith("/csm_registry_releases")),
    "a receipt that differs from its append-only descriptor must fail before Registry readback");

  const v2Registry = registryRow(v2);
  const { value: tamperedRegistry } = await readExternal({
    descriptor: v2,
    stored: v2Stored,
    registryOverrides: {
      registry_payload: { ...v2Registry.registry_payload, unreviewed_control: true }
    }
  });
  assert.equal(tamperedRegistry.external_identity_support, undefined,
    "an extra Registry payload key must fail the exact historical row contract");

  for (const [name, registryOverrides] of [
    ["registry version", { registry_version: "thin-path-external-identity-high-risers-v99" }],
    ["content hash", { content_sha256: "b".repeat(64) }],
    ["SEM standard", { sem_standard_version: "linear-cos-unreviewed" }]
  ]) {
    const { value } = await readExternal({ descriptor: v2, stored: v2Stored, registryOverrides });
    assert.equal(value.external_identity_support, undefined,
      `${name} drift must fail the exact Registry row contract`);
  }

  for (const [name, options] of [
    ["resolver", { resolutionOverrides: { resolver_version: "tampered-resolver" } }],
    ["composer", { outputOverrides: { composer_version: "tampered-composer" } }]
  ]) {
    const { value } = await readExternal({ descriptor: v2, stored: v2Stored, ...options });
    assert.equal(value.external_identity_support, undefined,
      `${name} drift must fail the persisted release tuple`);
  }

  const invalidFieldCorrection = storedReceipt(v2, {
    fieldDecisions: {
      ...v2Decisions,
      card_number: { ...baseDecisions.card_number, action: "CORRECT_CONFLICT" }
    }
  });
  const { value: invalidCorrection } = await readExternal({
    descriptor: v2, stored: invalidFieldCorrection
  });
  assert.equal(invalidCorrection.external_identity_support, undefined,
    "only year/set may carry a durable conflict-correction receipt");

  const wrongBasisCorrection = storedReceipt(v2, {
    matchMode: "EXACT_FOUR_ANCHOR", fieldDecisions: v2Decisions
  });
  const { value: wrongBasis } = await readExternal({
    descriptor: v2, stored: wrongBasisCorrection
  });
  assert.equal(wrongBasis.external_identity_support, undefined,
    "CORRECT_CONFLICT requires VERIFIED_ORIGINAL_SET match basis");

  const historicalCorrection = storedReceipt(v1, {
    fieldDecisions: { ...baseDecisions, year: v2Decisions.year }
  });
  const { value: v1Correction } = await readExternal({
    descriptor: v1, stored: historicalCorrection
  });
  assert.equal(v1Correction.external_identity_support, undefined,
    "historical v1 cannot acquire the v2 correction policy during readback");
}

// --- a stored title the current composer no longer reproduces is flagged ------
{
  const drifted = { ...record, output_title: "2025 Topps Chrome Something Else" };
  const view = await handleResolutionViewRequest({
    tenantId: "t1", assetId: "asset-1",
    dependencies: { ...deps, readRecord: async () => drifted }
  });
  assert.equal(view.composer.recomposed_matches_stored, false);
  assert.equal(view.composer.trace_reliable, false,
    "an operator must not be told a bracket was dropped for budget when the shipped title came from other code");
}

// --- stored Composer versions remain executable, including in review --------
{
  const replayed = composeResolutionView(legacyRecord);
  assert.equal(replayed.composer_version, THIN_COMPOSER_VERSION_V1);
  assert.equal(replayed.composed.title, legacyComposed.title);
  assert.doesNotMatch(replayed.composed.title, /\bBlue\b/,
    "the Glass Box must not reinterpret a historical v1 title with v2 compaction");
  assert.doesNotMatch(replayed.compose_corrected_title({ ...legacyFields, team: "Dodgers" }), /\bBlue\b/,
    "review recomposition must execute the stored v1 contract as well");

  const view = await handleResolutionViewRequest({
    tenantId: "t1", assetId: legacyRecord.asset_id,
    dependencies: { readRecord: async () => legacyRecord }
  });
  assert.equal(view.composer.composer_version, THIN_COMPOSER_VERSION_V1);
  assert.equal(view.composer.recomposed_matches_stored, true);
  assert.equal(view.composer.trace_reliable, true);
  assert.equal(view.owner_execution_receipt, null,
    "pre-v1 persisted runs stay readable without inventing a durable owner receipt");
  assert.equal(sha256Json(view), DE55_V1_REPLAY_VIEW_SHA256,
    "historical v1 rows also retain their complete de55 public projection");

  const historicalReview = await handleResolutionReviewRequest({
    tenantId: "t1", reviewerId: "u1",
    payload: {
      asset_id: legacyRecord.asset_id,
      verdict: REVIEW_VERDICT.CORRECTED,
      corrections: [{
        bracket: "set", canonical_field: "set", reason: CORRECTION_REASON.MISSED_VALUE,
        original_value: "", corrected_value: "Sapphire Selections"
      }]
    },
    dependencies: { readRecord: async () => legacyRecord, appendReview: async ({ review: value }) => value }
  });
  assert.equal(historicalReview.schema_version, CAPTURED_E1AE_RESOLUTION_REVIEW_VERSION);
  assert.match(historicalReview.corrected_title, /Sapphire Selections/);
  assert.equal(historicalReview.measurement_snapshot, undefined,
    "historical review-v1 remains reviewable without inventing a v2 denominator");
}

// --- a missing run is 404, not an empty view ---------------------------------
{
  await assert.rejects(
    () => handleResolutionViewRequest({ tenantId: "t1", assetId: "nope", dependencies: { readRecord: async () => null } }),
    (error) => error.statusCode === 404);
}

// --- review: the corrected title comes from corrected fields only -------------
{
  let appended = null;
  const review = await handleResolutionReviewRequest({
    tenantId: "t1", reviewerId: "u1",
    payload: {
      asset_id: futureReviewRecord.asset_id,
      verdict: REVIEW_VERDICT.CORRECTED,
      corrections: [{ bracket: "set", canonical_field: "set", reason: CORRECTION_REASON.MISSED_VALUE, original_value: "", corrected_value: "Sapphire Selections" }],
      // A reviewer's own title, which must be ignored entirely.
      corrected_title: "WHATEVER THE REVIEWER TYPED",
      measurement_snapshot: { schema_version: "client-forgery", brackets: [] }
    },
    dependencies: {
      ...futureReviewDeps,
      appendReview: async ({ review: r }) => { appended = r; return r; }
    }
  });
  assert.match(review.corrected_title, /Sapphire Selections/);
  assert.ok(!/WHATEVER/.test(review.corrected_title),
    "a title in the payload must never reach the record");
  assert.equal(review.original_title, futureReviewRecord.output_title,
    "the shipped output is preserved");
  assert.ok(appended, "the review is persisted");
  assert.equal(appended.revision_sha256, review.revision_sha256);
  // Provenance is filled from the stored run, not from the client.
  assert.equal(review.resolution_id, futureReviewRecord.resolution_id);
  assert.equal(review.output_id, futureReviewRecord.output_id);
  assert.equal(review.reviewer_id, "u1");
  assert.equal(review.measurement_basis, "FIELD_REVIEWED");
  assert.equal(review.measurement_snapshot.asset_id, futureReviewRecord.asset_id);
  assert.notEqual(review.measurement_snapshot.schema_version, "client-forgery",
    "the server-replayed view owns the measurement denominator");
  assert.match(review.measurement_snapshot_sha256, /^[0-9a-f]{64}$/);
}

// --- review: an approval cannot carry corrections ----------------------------
{
  await assert.rejects(() => handleResolutionReviewRequest({
    tenantId: "t1", reviewerId: "u1",
    payload: { asset_id: futureReviewRecord.asset_id, verdict: REVIEW_VERDICT.APPROVED, corrections: [{ bracket: "set", reason: CORRECTION_REASON.WRONG_VALUE, corrected_value: "x" }] },
    dependencies: futureReviewDeps
  }), /approved_with_corrections/);
}

console.log("csm-resolution-api.test.mjs OK");

// COS-42 (founder, 2026-08-04): "Field-level semantic approval/correction is a
// separate trusted reviewer/admin workflow; it is not the default writer
// workflow." A writer's title edit is cleaned commercial feedback, and the
// route from editing a title to rewriting canonical fields must not exist.
{
  const { TENANT_PERMISSIONS, permissionScopeFor } = await import("../lib/tenant/permissions.mjs");
  const REVIEW = TENANT_PERMISSIONS.REVIEW_SEMANTIC_FIELDS;
  assert.ok(REVIEW, "the review workflow needs its own permission, not a borrowed one");
  assert.equal(permissionScopeFor("WRITER", REVIEW), "NONE",
    "a writer must not be able to approve or correct canonical fields");
  assert.notEqual(permissionScopeFor("OWNER", REVIEW), "NONE");
  assert.notEqual(permissionScopeFor("MANAGER", REVIEW), "NONE");
  // The separation is the point: writers keep the title edit they had.
  assert.notEqual(permissionScopeFor("WRITER", TENANT_PERMISSIONS.EDIT_TITLE), "NONE",
    "writers still edit titles; that is commercial feedback, not semantic truth");

  // And the endpoint must ask for the reviewer permission, not the writer one.
  const source = await (await import("node:fs/promises")).readFile(
    new URL("../api/csm-resolution-view.js", import.meta.url), "utf8");
  assert.match(source, /TENANT_PERMISSIONS\.REVIEW_SEMANTIC_FIELDS/,
    "the POST path gates on the reviewer permission");
  // The USAGE, not any mention: the comment above that line names the two
  // non-existent constants it replaced, and a whole-file regex would fail on
  // the explanation rather than on the code.
  assert.ok(!/TENANT_PERMISSIONS\.(WRITE|READ)_LISTING/.test(source),
    "those constants never existed and read as undefined at the permission check");
}

console.log("csm-resolution-api reviewer-workflow assertions OK");
