import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const html = await readFile("app/index.html", "utf8");
const js = await readFile("app/listing-copilot.js", "utf8");
const css = await readFile("app/listing-copilot.css", "utf8");
const api = await readFile("api/listing-copilot-title.js", "utf8");

assert.match(html, /id="providerControl"/, "provider segmented control should exist");
assert.match(html, /id="providerStatusText"/, "provider status text should exist");
assert.match(js, /fetch\("\/api\/listing-provider-status"/, "frontend should load provider status from the server");
assert.match(js, /state\.selectedProvider/, "frontend should keep selected provider in state");
assert.match(js, /state\.selectedProvider = payload\.default_provider \|\| ""/, "frontend should use the server default provider as the selected provider");
assert.doesNotMatch(js, /state\.selectedProvider\s*=\s*["']openai_legacy["']/, "frontend must not default-select GPT-4.1 legacy");
assert.match(js, /body\.provider = provider/, "title requests should include the selected provider");
assert.match(js, /body\.explicitEmergency = Boolean/, "GPT single-provider requests should be explicit");
assert.match(js, /provider === "openai_legacy"/, "OpenAI single-provider path should be explicit");
assert.match(js, /providerCascadeText/, "frontend should show GPT primary and Agnes auxiliary status for cascade");
assert.match(js, /主路径 GPT-4\.1/, "cascade control should identify GPT-4.1 as the primary path");
assert.match(js, /fetch\("\/api\/listing-image-upload-url"/, "frontend should request server-signed upload URLs");
assert.match(js, /signed_upload_url/, "frontend should upload through signed URLs");
assert.match(js, /signatureHex/, "frontend should send first-byte signatures before receiving signed upload URLs");
assert.match(js, /width: dimensions\.width/, "frontend should send image width before receiving signed upload URLs");
assert.match(js, /height: dimensions\.height/, "frontend should send image height before receiving signed upload URLs");
assert.match(js, /fetch\("\/api\/listing-image-verify-upload"/, "frontend should verify uploaded objects server-side before provider calls");
assert.match(js, /storageVerified/, "frontend should preserve server-side storage verification state");
assert.match(js, /storageVerificationToken/, "frontend should pass server-issued storage verification tokens to title requests");
assert.match(js, /objectPath/, "frontend should preserve storage object paths for provider calls");
assert.match(js, /serializableAssetImage/, "frontend should strip browser-only File objects from title payloads");
assert.match(js, /imageHasVerifiedStorageReference/, "frontend should detect storage-backed images");
assert.match(js, /dataUrl: useStorageReference \? "" : image\.dataUrl/, "storage-backed title requests should not send large Base64 image JSON");
assert.match(js, /captureQuality: summarizeAssetImageQuality/, "title requests should include capture quality summaries");
assert.match(js, /imageQuality/, "image records should carry first-pass quality metrics");
assert.match(js, /planTargetedCrops/, "frontend should plan targeted crops from quality results");
assert.match(js, /targetedCrops/, "frontend should carry targeted crop images alongside originals");
assert.match(js, /sourceBlob/, "derived crop images should be uploadable without service credentials");
assert.match(js, /storageRoleForImage\(image, imageIndex\)/, "storage upload should use crop-specific image roles");
assert.match(api, /primaryImagesFromImages/, "title API should separate primary card images from derived crops");
assert.match(api, /verifyListingImageVerificationToken/, "title API should require server-issued storage verification tokens before signed read URLs");
assert.match(api, /readListingImageVerificationRecord/, "title API should allow durable server verification records for later reprocessing");
assert.match(api, /Listing image storage reference has not been verified/, "title API should reject unverified storage object references");
assert.match(api, /createAgnesFocusedRereadRunner/, "title API should wire focused Agnes rereads through Evidence Completion");
assert.match(api, /const signedImages = await imagesWithSignedReadUrls\(payload\.images \|\| \[\], timingContext\)/, "OpenAI fallback should use signed storage read URLs instead of requiring Base64 JSON");
assert.match(api, /signedImages: recognitionPreflight\.signedImages/, "provider calls should reuse signed URLs created during recognition preflight");
assert.match(api, /tryProviderFastPath\(\s*cascadeResult,/, "cascade provider should try fast path before evidence completion");
assert.match(api, /if \(fastPathResult\) return fastPathResult;/, "cascade fast path should skip slow completion when identity is already resolved");
assert.match(api, /runFocusedVisionImpl/, "Evidence Completion should receive the focused vision runner explicitly");
assert.match(api, /optional bounded derived crop images/, "title API should accept derived crop images without allowing unbounded inputs");
assert.match(js, /moduleSummary\(result\)/, "frontend should render writer-facing modules from the title API");
assert.match(js, /result\.modules/, "frontend should read module output from deterministic renderer responses");
assert.match(js, /data-module-input/, "writer modules should expose editable module text controls");
assert.match(js, /publicationGateNotice\(result\)/, "frontend should show the partial publication gate contract");
assert.match(js, /writer_required_fields/, "frontend should surface unresolved writer-required fields");
assert.match(js, /fetch\("\/api\/listing-render-title"/, "module edits should rerender through the server renderer endpoint");
assert.match(js, /module_edit/, "module edit requests should preserve the explicit edit boundary");
assert.match(js, /title_override/, "manual title overrides should be tracked separately from resolved fields");
assert.match(js, /useRenderedTitle/, "writers should be able to replace an override with the rerendered module title");
assert.match(js, /generated_resolved_fields/, "feedback saves should include generated resolved snapshots");
assert.match(js, /corrected_resolved_fields/, "feedback saves should include corrected resolved snapshots");
assert.match(js, /review_duration_ms/, "feedback saves should include review duration");
assert.match(js, /reviewImageReference/, "feedback saves should pass storage object references without browser-only objects");
assert.doesNotMatch(js, /标题未修改，未写入记忆/, "unchanged reviews must not be skipped client-side");
assert.match(js, /payload\.retention_skipped/, "frontend should recognize feedback responses that are intentionally not retained");
assert.match(js, /feedbackStatus = retentionSkipped \? "skipped" : "saved"/, "skipped feedback retention must not be treated as a saved review");
assert.match(js, /未留存/, "skipped feedback retention should be visible to operators");
assert.match(js, /payload\.record\?\.review\?\.id/, "frontend should keep the durable review id before publishing");
assert.match(js, /payload\.record\?\.review\?\.approved_at/, "frontend should require server approval time before publishing");
assert.match(js, /buildListingDraft/, "frontend should build a ListingDraft instead of publishing raw AI output");
assert.match(js, /review_status: "APPROVED"/, "frontend publish draft should be explicitly approved");
assert.match(js, /fetch\("\/api\/listing-publish-draft"/, "frontend should publish approved drafts through the server API");
assert.match(js, /data-publish-draft/, "approved reviews should expose a publish action");
assert.match(js, /destination: "mock_b_end"/, "frontend should only target the mock B-end adapter");
assert.match(js, /dry_run: true/, "mock publish requests should remain dry-run from the UI");
assert.match(js, /data-emergency-retry/, "failed assets should expose explicit GPT single-provider retry control");
assert.match(js, /retryAssetWithEmergency/, "GPT single-provider retry should be a separate action");
assert.match(js, /renderProviderControl/, "provider controls should be rendered from server status");
assert.match(js, /providerSmokeText/, "frontend should summarize provider smoke capability status");
assert.match(js, /json_baseline_verified/, "frontend should surface Agnes JSON smoke verification status");
assert.match(js, /tool_call_verified/, "frontend should surface Agnes tool-call smoke verification status");
assert.match(js, /provider-smoke/, "provider cards should render sanitized smoke status text");
assert.match(css, /\.provider-option\.active/, "selected provider should have a visible active state");
assert.match(css, /\.provider-option:disabled/, "disabled providers should render as unavailable");
assert.match(css, /\.provider-smoke/, "smoke status should have a stable compact style");
assert.match(css, /\.writer-modules/, "writer-facing modules should have a compact layout");
assert.match(css, /\.writer-module\.needs-review/, "module review state should be visible");
assert.match(css, /\.publication-gate/, "partial writer draft gate should be visible");
assert.match(css, /\.title-override-note/, "title override state should be visible");
assert.match(css, /\.publish-button/, "mock publish button should have a distinct approved-action style");
assert.match(css, /\.publish-status/, "mock publish status should be visible after publishing");
assert.doesNotMatch(html, /name="model_id"|name="endpoint"|id="modelId"|id="providerEndpoint"/i, "frontend must not expose arbitrary model or endpoint inputs");

console.log("provider UI tests passed");
