import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const html = await readFile("app/index.html", "utf8");
const js = await readFile("app/listing-copilot.js", "utf8");
const css = await readFile("app/listing-copilot.css", "utf8");
const api = await readFile("api/listing-copilot-title.js", "utf8");
const providerRegistry = await readFile("lib/listing/providers/provider-registry.mjs", "utf8");

assert.match(html, /id="providerControl"/, "provider segmented control should exist");
assert.match(html, /id="providerStatusText"/, "provider status text should exist");
assert.match(js, /fetch\("\/api\/listing-provider-status"/, "frontend should load provider status from the server");
assert.match(js, /state\.selectedProvider/, "frontend should keep selected provider in state");
assert.match(js, /state\.selectedProvider = payload\.default_provider \|\| ""/, "frontend should use the server default provider as the selected provider");
assert.doesNotMatch(js, /state\.selectedProvider\s*=\s*["']openai_legacy["']/, "frontend must use the server default rather than hard-code a provider");
assert.match(js, /body\.provider = provider/, "title requests should include the selected provider");
assert.match(js, /defaultProviderOptions/, "frontend should centralize default provider options");
assert.match(js, /single_model_fast:\s*false/, "frontend default path should not skip evidence completion");
assert.match(js, /enable_evidence_completion:\s*true/, "frontend default path should use evidence completion");
assert.match(js, /enable_stored_visual_features:\s*false/, "frontend default path should not use legacy visual vector candidates");
assert.match(js, /enable_query_visual_embeddings:\s*false/, "frontend default path should not request legacy query embeddings");
assert.match(js, /enable_vector_retrieval:\s*false/, "vector retrieval must be explicitly enabled by feature flag");
assert.match(js, /vector_retrieval_mode:\s*"off"/, "vector retrieval should default to off");
assert.match(js, /vectorCandidateNotice/, "writer UI should expose lightweight vector candidate status");
assert.match(js, /vector_prompt_assist_used/, "writer UI should show whether vector candidates entered the GPT prompt");
assert.match(js, /provider_options:\s*{/, "title requests should include provider options");
assert.match(js, /body\.explicitEmergency = Boolean/, "legacy explicit flag should remain backward-compatible");
assert.match(js, /provider === "openai_legacy"/, "OpenAI provider path should remain explicit in request payloads");
assert.match(js, /providerCascadeText/, "frontend should render concise provider role text");
assert.match(js, /GPT-4\.1 mini/, "provider control should identify GPT provider labels");
assert.doesNotMatch(js, /Agnes|cascade_fast|格式失败兜底/, "frontend must not expose Agnes or mixed-model cascade controls");
assert.match(js, /fetch\("\/api\/listing-image-upload-url"/, "frontend should request server-signed upload URLs");
assert.match(js, /signed_upload_url/, "frontend should upload through signed URLs");
assert.match(js, /signatureHex/, "frontend should send first-byte signatures before receiving signed upload URLs");
assert.match(js, /width: dimensions\.width/, "frontend should send image width before receiving signed upload URLs");
assert.match(js, /height: dimensions\.height/, "frontend should send image height before receiving signed upload URLs");
assert.match(js, /fetch\("\/api\/listing-image-verify-upload"/, "frontend should verify uploaded objects server-side before provider calls");
assert.match(js, /storageVerified/, "frontend should preserve server-side storage verification state");
assert.match(js, /storageVerificationToken/, "frontend should pass server-issued storage verification tokens to title requests");
assert.match(js, /objectPath/, "frontend should preserve storage object paths for provider calls");
assert.match(js, /serializableAssetImage/, "frontend should strip browser-only File objects from title payloads");
assert.match(js, /imageHasVerifiedStorageReference/, "frontend should detect storage-backed images");
assert.match(js, /dataUrl: useStorageReference \? "" : image\.dataUrl/, "storage-backed title requests should not send large Base64 image JSON");
assert.match(js, /captureQuality: summarizeAssetImageQuality/, "title requests should include capture quality summaries");
assert.match(js, /imageQuality/, "image records should carry first-pass quality metrics");
assert.match(js, /planTargetedCrops/, "frontend should plan targeted crops from quality results");
assert.match(js, /targetedCrops/, "frontend should carry targeted crop images alongside originals");
assert.match(js, /fieldCropStrip/, "frontend should render field crop thumbnails for writer review");
assert.match(js, /modalImagesForAsset/, "image modal should include field crops as reviewable evidence");
assert.match(js, /cropMetadata/, "frontend should preserve crop metadata through request and review payloads");
assert.match(js, /sourceBlob/, "derived crop images should be uploadable without service credentials");
assert.match(js, /storageRoleForImage\(image, imageIndex\)/, "storage upload should use crop-specific image roles");
assert.match(api, /primaryImagesFromImages/, "title API should separate primary card images from derived crops");
assert.match(api, /verifyListingImageVerificationToken/, "title API should require server-issued storage verification tokens before signed read URLs");
assert.match(api, /readListingImageVerificationRecord/, "title API should allow durable server verification records for later reprocessing");
assert.match(api, /Listing image storage reference has not been verified/, "title API should reject unverified storage object references");
assert.doesNotMatch(api, /createGptCriticalVerifierRunner|createAgnesTitle|createCascadeFastTitle|analyzeCardEvidenceWithAgnes/, "title API should not wire automatic mixed-model or Agnes paths");
assert.doesNotMatch(providerRegistry, /ENABLE_AGNES_AUTO_VERIFIER|ENABLE_FAST_CASCADE_PROVIDER|cascade_fast|AGNES/i, "provider registry should only expose the active GPT provider");
assert.match(api, /const signedImages = await imagesWithSignedReadUrls\(payload\.images \|\| \[\], timingContext\)/, "OpenAI fallback should use signed storage read URLs instead of requiring Base64 JSON");
assert.match(api, /signedImages: recognitionPreflight\.signedImages/, "provider calls should reuse signed URLs created during recognition preflight");
assert.doesNotMatch(api, /tryProviderFastPath\(\s*cascadeResult,/, "cascade fast path should not exist");
assert.match(api, /if \(fastPathResult\) return fastPathResult;/, "cascade fast path should skip slow completion when identity is already resolved");
assert.match(api, /singleModelFastPathEnabled/, "title API should expose a single-model fast path switch");
assert.match(api, /envFlag\(env, "ENABLE_SINGLE_MODEL_FAST_PATH", false\)/, "title API should default to model plus evidence completion");
assert.match(api, /singleModelDraftPath/, "single-model provider requests should be able to skip Evidence Completion");
assert.match(api, /skipped_evidence_completion: true/, "single-model fast drafts should record skipped Evidence Completion");
assert.match(api, /assist_shadow_no_prompt_safe_candidates/, "assist-enabled requests with no prompt-safe candidates should stay in shadow-only mode");
assert.match(api, /assist_shadow_only: assistShadowOnly/, "assist shadow-only drafts should be distinguishable from provider fast path");
assert.match(api, /allowWhenEvidenceCompletion: assistShadowOnly/, "assist shadow-only drafts should skip Evidence Completion without enabling unsafe candidate assist");
assert.match(api, /assist_shadow_retrieval_failed/, "assist shadow telemetry failures should not fail the GPT draft");
assert.match(api, /ENABLE_EVIDENCE_COMPLETION/, "slow Evidence Completion should be controlled by an explicit env flag");
assert.match(api, /vectorRetrievalActive\(env, options\)/, "title API should only run visual vector lookup when vector retrieval is active");
assert.match(api, /envFlag\(env, "ENABLE_STORED_VISUAL_FEATURE_LOOKUP", false\)/, "legacy stored visual lookup should default off");
assert.doesNotMatch(api, /runFocusedVisionImpl:\s*createGptCriticalVerifierRunner|runFocusedVisionImpl:\s*createAgnes/, "automatic second-model focused vision should not be wired from the title API");
assert.match(api, /optional bounded derived crop images/, "title API should accept derived crop images without allowing unbounded inputs");
assert.match(js, /moduleSummary\(result\)/, "frontend should render writer-facing modules from the title API");
assert.match(js, /result\.modules/, "frontend should read module output from deterministic renderer responses");
assert.match(js, /data-module-input/, "writer modules should expose editable module text controls");
assert.match(js, /publicationGateNotice\(result\)/, "frontend should show the partial publication gate contract");
assert.match(js, /writer_required_fields/, "frontend should surface unresolved writer-required fields");
assert.match(js, /modelQuickApprovalCandidate/, "frontend should group model quick-approval candidates for writer review");
assert.match(js, /model_quick_review_recommended/, "frontend should treat model quick-review as a writer queue, not direct publishing");
assert.match(js, /低触审核/, "frontend should label low-risk model results as a low-touch writer review queue");
assert.match(js, /data-quick-approve-publish/, "writer quick approval should expose a one-click approve-and-publish action");
assert.match(js, /quickApproveAndPublish/, "quick approval should save the writer review before publishing");
assert.match(js, /fetch\("\/api\/listing-render-title"/, "module edits should rerender through the server renderer endpoint");
assert.match(js, /module_edit/, "module edit requests should preserve the explicit edit boundary");
assert.match(js, /title_override/, "manual title overrides should be tracked separately from resolved fields");
assert.match(js, /useRenderedTitle/, "writers should be able to replace an override with the rerendered module title");
assert.match(js, /generated_resolved_fields/, "feedback saves should include generated resolved snapshots");
assert.match(js, /corrected_resolved_fields/, "feedback saves should include corrected resolved snapshots");
assert.match(js, /review_duration_ms/, "feedback saves should include review duration");
assert.match(js, /reviewImageReference/, "feedback saves should pass storage object references without browser-only objects");
assert.doesNotMatch(js, /标题未修改，未写入记忆/, "unchanged reviews must not be skipped client-side");
assert.match(js, /payload\.retention_skipped/, "frontend should recognize feedback responses that are intentionally not retained");
assert.match(js, /feedbackStatus = retentionSkipped \? "skipped" : "saved"/, "skipped feedback retention must not be treated as a saved review");
assert.match(js, /未留存/, "skipped feedback retention should be visible to operators");
assert.match(js, /payload\.record\?\.review\?\.id/, "frontend should keep the durable review id before publishing");
assert.match(js, /payload\.record\?\.review\?\.approved_at/, "frontend should require server approval time before publishing");
assert.match(js, /buildListingDraft/, "frontend should build a ListingDraft instead of publishing raw AI output");
assert.match(js, /review_status: "APPROVED"/, "frontend publish draft should be explicitly approved");
assert.match(js, /fetch\("\/api\/listing-publish-draft"/, "frontend should publish approved drafts through the server API");
assert.match(js, /data-publish-draft/, "approved reviews should expose a publish action");
assert.match(js, /destination: "mock_b_end"/, "frontend should only target the mock B-end adapter");
assert.match(js, /dry_run: true/, "mock publish requests should remain dry-run from the UI");
assert.match(js, /data-emergency-retry/, "failed assets should expose explicit GPT single-provider retry control");
assert.match(js, /retryAssetWithEmergency/, "GPT single-provider retry should be a separate action");
assert.match(js, /renderProviderControl/, "provider controls should be rendered from server status");
assert.match(css, /\.provider-option\.active/, "selected provider should have a visible active state");
assert.match(css, /\.provider-option:disabled/, "disabled providers should render as unavailable");
assert.match(css, /\.writer-modules/, "writer-facing modules should have a compact layout");
assert.match(css, /\.writer-module\.needs-review/, "module review state should be visible");
assert.match(css, /\.field-crop-strip/, "field crop evidence strip should have a stable layout");
assert.match(css, /\.publication-gate/, "partial writer draft gate should be visible");
assert.match(css, /\.title-override-note/, "title override state should be visible");
assert.match(css, /\.publish-button/, "mock publish button should have a distinct approved-action style");
assert.match(css, /\.publish-status/, "mock publish status should be visible after publishing");
assert.doesNotMatch(html, /name="model_id"|name="endpoint"|id="modelId"|id="providerEndpoint"/i, "frontend must not expose arbitrary model or endpoint inputs");

console.log("provider UI tests passed");
