begin;

-- One recognition session owns at most one durable job per stage. This is the
-- final storage backstop; the RPC wrapper below rejects duplicate input before
-- the first write so batch.item_count can never disagree with durable jobs.
do $$
begin
  if exists (
    select 1
    from public.v4_recognition_jobs
    group by tenant_id, recognition_session_id, job_type
    having count(*) > 1
  ) then
    raise exception using
      errcode = '23505',
      message = 'v4_queue_duplicate_session_stage_identity_exists';
  end if;
end;
$$;

create unique index if not exists v4_recognition_jobs_tenant_session_stage_uidx
  on public.v4_recognition_jobs (tenant_id, recognition_session_id, job_type);

comment on index public.v4_recognition_jobs_tenant_session_stage_uidx is
  'Atomic duplicate-work guard: one job per tenant recognition session and stage.';

-- Client batch/idempotency tokens are transport metadata, never queue-work
-- identity. Queue sessions remain writer-owned; exact-result cache and
-- in-flight coalescing independently deduplicate Provider work across writers.
-- Protect the server-verifiable writer workflow tuple for its full lifetime.
-- Only authorizeFreshManualRetryJobs may add authorized_retry_of_job_id and
-- therefore create a new server-owned retry lineage after terminal failure.
do $$
begin
  if exists (
    select 1
    from public.v4_recognition_jobs
    where nullif(pg_catalog.btrim(payload ->> 'image_generation_id'), '') is not null
      and nullif(pg_catalog.btrim(payload ->> 'image_set_sha256'), '') is not null
      and nullif(pg_catalog.btrim(payload ->> 'queue_decision_fingerprint'), '') is not null
    group by
      tenant_id,
      operator_id,
      asset_id,
      pg_catalog.btrim(payload ->> 'image_generation_id'),
      pg_catalog.lower(pg_catalog.btrim(payload ->> 'image_set_sha256')),
      pg_catalog.lower(pg_catalog.btrim(payload ->> 'queue_decision_fingerprint')),
      job_type,
      coalesce(nullif(pg_catalog.btrim(payload ->> 'authorized_retry_of_job_id'), ''), '')
    having count(*) > 1
  ) then
    raise exception using
      errcode = '23505',
      message = 'v4_queue_duplicate_semantic_work_exists';
  end if;
end;
$$;

create unique index if not exists v4_recognition_jobs_semantic_work_uidx
  on public.v4_recognition_jobs (
    tenant_id,
    operator_id,
    asset_id,
    (pg_catalog.btrim(payload ->> 'image_generation_id')),
    (pg_catalog.lower(pg_catalog.btrim(payload ->> 'image_set_sha256'))),
    (pg_catalog.lower(pg_catalog.btrim(payload ->> 'queue_decision_fingerprint'))),
    job_type,
    (coalesce(nullif(pg_catalog.btrim(payload ->> 'authorized_retry_of_job_id'), ''), ''))
  )
  where nullif(pg_catalog.btrim(payload ->> 'image_generation_id'), '') is not null
    and nullif(pg_catalog.btrim(payload ->> 'image_set_sha256'), '') is not null
    and nullif(pg_catalog.btrim(payload ->> 'queue_decision_fingerprint'), '') is not null;

comment on index public.v4_recognition_jobs_semantic_work_uidx is
  'One lifetime writer workflow job per tenant, operator, asset, verified image generation/content, immutable decision, stage, and server-authorized retry lineage; client nonces are excluded and Provider work is deduplicated separately.';

-- Recognition acceptance and paid OCR intent must commit in one database
-- transaction. The actual OCR call remains asynchronous; a lost Vercel
-- waitUntil or a bundle that becomes ready later cannot erase this intent.
create table if not exists public.preingestion_recognition_commit_outbox (
  outbox_id bigint generated by default as identity primary key,
  tenant_id text not null,
  asset_id text not null,
  image_generation_id text not null,
  image_set_sha256 text not null,
  queue_decision_fingerprint text not null,
  identity_result_cache_key text,
  identity_cache_image_generation_hash text,
  identity_cache_read_allowed boolean not null default true,
  writer_final_replay_allowed boolean not null default true,
  authorized_retry_of_job_id text not null default '',
  recognition_batch_id text not null,
  recognition_job_id text not null,
  status text not null default 'queued',
  attempts integer not null default 0,
  max_attempts integer not null default 20,
  next_attempt_at timestamptz not null default pg_catalog.clock_timestamp(),
  lease_owner text,
  lease_expires_at timestamptz,
  last_error text,
  created_at timestamptz not null default pg_catalog.clock_timestamp(),
  updated_at timestamptz not null default pg_catalog.clock_timestamp(),
  constraint preingestion_recognition_commit_outbox_status_chk
    check (status in ('queued', 'processing', 'completed', 'dead_letter')),
  constraint preingestion_recognition_commit_outbox_attempts_chk
    check (attempts between 0 and max_attempts and max_attempts between 1 and 100),
  constraint preingestion_recognition_commit_outbox_lease_chk
    check ((lease_owner is null) = (lease_expires_at is null)),
  constraint preingestion_recognition_commit_outbox_image_sha_chk
    check (image_set_sha256 ~ '^[0-9a-f]{64}$'),
  constraint preingestion_recognition_commit_outbox_decision_sha_chk
    check (queue_decision_fingerprint ~ '^[0-9a-f]{64}$'),
  constraint preingestion_recognition_commit_outbox_cache_key_chk
    check (identity_result_cache_key is null or identity_result_cache_key ~ '^[0-9a-f]{64}$'),
  constraint preingestion_recognition_commit_outbox_cache_generation_chk
    check (identity_cache_image_generation_hash is null or identity_cache_image_generation_hash ~ '^[0-9a-f]{64}$'),
  constraint preingestion_recognition_commit_outbox_retry_lineage_chk
    check (authorized_retry_of_job_id = '' or authorized_retry_of_job_id ~ '^[A-Za-z0-9][A-Za-z0-9_-]{0,159}$'),
  unique (
    tenant_id,
    asset_id,
    image_generation_id,
    image_set_sha256,
    queue_decision_fingerprint,
    authorized_retry_of_job_id
  )
);

create index if not exists preingestion_recognition_commit_outbox_claim_idx
  on public.preingestion_recognition_commit_outbox (next_attempt_at, created_at, outbox_id)
  where status in ('queued', 'processing');

alter table public.preingestion_recognition_commit_outbox enable row level security;
revoke all on table public.preingestion_recognition_commit_outbox from public, anon, authenticated;
grant select, insert, update on table public.preingestion_recognition_commit_outbox to service_role;

drop trigger if exists track_c_tenant_id_immutable on public.preingestion_recognition_commit_outbox;
create trigger track_c_tenant_id_immutable
before update of tenant_id on public.preingestion_recognition_commit_outbox
for each row execute function private.prevent_tenant_change();

create or replace function public.claim_preingestion_recognition_commit_outbox(
  p_limit integer,
  p_lease_owner text,
  p_tenant_id text default null,
  p_asset_id text default null
)
returns setof public.preingestion_recognition_commit_outbox
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_limit integer := greatest(1, least(coalesce(p_limit, 4), 20));
  v_existing integer := 0;
begin
  if nullif(pg_catalog.btrim(p_lease_owner), '') is null
     or pg_catalog.length(p_lease_owner) > 160 then
    return;
  end if;

  -- A worker can disappear after consuming its final allowed attempt. Once
  -- that lease expires, make the terminal state explicit instead of leaving a
  -- permanently unclaimable `processing` row. The same guard also repairs any
  -- legacy queued row whose attempt budget was already exhausted.
  update public.preingestion_recognition_commit_outbox outbox
  set status = 'dead_letter',
      lease_owner = null,
      lease_expires_at = null,
      last_error = coalesce(outbox.last_error, 'lease_expired_after_max_attempts'),
      updated_at = pg_catalog.clock_timestamp()
  where outbox.attempts >= outbox.max_attempts
    and (
      (outbox.status = 'processing' and outbox.lease_expires_at <= pg_catalog.clock_timestamp())
      or outbox.status = 'queued'
    );

  -- An RPC response can be lost after the lease commits. Repeating the same
  -- request returns its existing lease instead of claiming/incrementing twice.
  return query
  select outbox.*
  from public.preingestion_recognition_commit_outbox outbox
  where outbox.status = 'processing'
    and outbox.lease_owner = p_lease_owner
    and outbox.lease_expires_at > pg_catalog.clock_timestamp()
    and (nullif(pg_catalog.btrim(p_tenant_id), '') is null or outbox.tenant_id = p_tenant_id)
    and (nullif(pg_catalog.btrim(p_asset_id), '') is null or outbox.asset_id = p_asset_id)
  order by outbox.outbox_id
  limit v_limit;
  get diagnostics v_existing = row_count;

  if v_existing >= v_limit then
    return;
  end if;

  return query
  with candidates as (
    select outbox.outbox_id
    from public.preingestion_recognition_commit_outbox outbox
    where (
        outbox.status = 'queued'
        or (
          outbox.status = 'processing'
          and outbox.lease_expires_at <= pg_catalog.clock_timestamp()
        )
      )
      and outbox.next_attempt_at <= pg_catalog.clock_timestamp()
      and outbox.attempts < outbox.max_attempts
      and (nullif(pg_catalog.btrim(p_tenant_id), '') is null or outbox.tenant_id = p_tenant_id)
      and (nullif(pg_catalog.btrim(p_asset_id), '') is null or outbox.asset_id = p_asset_id)
    order by outbox.next_attempt_at, outbox.created_at, outbox.outbox_id
    for update skip locked
    limit (v_limit - v_existing)
  )
  update public.preingestion_recognition_commit_outbox outbox
  set status = 'processing',
      attempts = outbox.attempts + 1,
      lease_owner = p_lease_owner,
      lease_expires_at = pg_catalog.clock_timestamp() + interval '90 seconds',
      updated_at = pg_catalog.clock_timestamp()
  from candidates
  where outbox.outbox_id = candidates.outbox_id
  returning outbox.*;
end;
$$;

create or replace function public.settle_preingestion_recognition_commit_outbox(
  p_outbox_id bigint,
  p_lease_owner text,
  p_completed boolean,
  p_error text default null,
  p_retry_after_seconds integer default 5
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row public.preingestion_recognition_commit_outbox%rowtype;
begin
  update public.preingestion_recognition_commit_outbox outbox
  set status = case
        when p_completed then 'completed'
        when outbox.attempts >= outbox.max_attempts then 'dead_letter'
        else 'queued'
      end,
      next_attempt_at = case
        when p_completed then outbox.next_attempt_at
        else pg_catalog.clock_timestamp()
          + pg_catalog.make_interval(secs => greatest(1, least(coalesce(p_retry_after_seconds, 5), 3600)))
      end,
      lease_owner = null,
      lease_expires_at = null,
      last_error = nullif(pg_catalog.left(coalesce(p_error, ''), 500), ''),
      updated_at = pg_catalog.clock_timestamp()
  where outbox.outbox_id = p_outbox_id
    and outbox.status = 'processing'
    and outbox.lease_owner = p_lease_owner
  returning outbox.* into v_row;

  if found then
    return pg_catalog.jsonb_build_object(
      'settled', true,
      'outbox_id', v_row.outbox_id,
      'status', v_row.status,
      'attempts', v_row.attempts
    );
  end if;

  select outbox.* into v_row
  from public.preingestion_recognition_commit_outbox outbox
  where outbox.outbox_id = p_outbox_id;
  return pg_catalog.jsonb_build_object(
    'settled', v_row.outbox_id is not null and (
      (p_completed and v_row.status = 'completed')
      or (not p_completed and v_row.status in ('queued', 'dead_letter'))
    ),
    'outbox_id', p_outbox_id,
    'status', v_row.status,
    'attempts', v_row.attempts
  );
end;
$$;

revoke all on function public.claim_preingestion_recognition_commit_outbox(integer, text, text, text)
  from public, anon, authenticated;
grant execute on function public.claim_preingestion_recognition_commit_outbox(integer, text, text, text)
  to service_role;
revoke all on function public.settle_preingestion_recognition_commit_outbox(bigint, text, boolean, text, integer)
  from public, anon, authenticated;
grant execute on function public.settle_preingestion_recognition_commit_outbox(bigint, text, boolean, text, integer)
  to service_role;

-- Recognition-triggered OCR enqueue has a stricter contract than the generic
-- pre-ingestion inserter: duplicate rows are executable only when they are
-- already queued/running/succeeded. A terminal row may be revived exactly
-- once per server-authorized recognition retry lineage; ordinary repeats and
-- active leases are never reset or double-run.
create or replace function public.enqueue_recognition_preingestion_ocr_jobs(
  p_jobs jsonb,
  p_authorized_retry_lineage_id text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_job_count integer := case
    when pg_catalog.jsonb_typeof(p_jobs) = 'array' then pg_catalog.jsonb_array_length(p_jobs)
    else 0
  end;
  v_retry_lineage text := coalesce(nullif(pg_catalog.btrim(p_authorized_retry_lineage_id), ''), '');
  v_inserted integer := 0;
  v_requeued integer := 0;
  v_state_count integer := 0;
  v_runnable integer := 0;
  v_succeeded integer := 0;
  v_blocked_terminal integer := 0;
  v_identity_mismatch integer := 0;
begin
  if v_job_count < 1 or v_job_count > 32 then
    return pg_catalog.jsonb_build_object('saved', false, 'reason', 'ocr_job_request_invalid');
  end if;
  if v_retry_lineage <> '' and v_retry_lineage !~ '^[A-Za-z0-9][A-Za-z0-9_-]{0,159}$' then
    return pg_catalog.jsonb_build_object('saved', false, 'reason', 'authorized_retry_lineage_invalid');
  end if;
  if exists (
    select 1
    from pg_catalog.jsonb_array_elements(p_jobs) job_item
    where pg_catalog.jsonb_typeof(job_item) <> 'object'
       or nullif(pg_catalog.btrim(job_item ->> 'tenant_id'), '') is null
       or nullif(pg_catalog.btrim(job_item ->> 'asset_id'), '') is null
       or nullif(pg_catalog.btrim(job_item ->> 'bundle_id'), '') is null
       or nullif(pg_catalog.btrim(job_item ->> 'job_key'), '') is null
       or pg_catalog.btrim(job_item ->> 'job_key') !~ '^ocr:[A-Za-z0-9._-]+:[A-Za-z0-9._-]+:'
       or pg_catalog.lower(pg_catalog.btrim(job_item ->> 'job_type')) <> 'ocr_crop_verification'
       or pg_catalog.jsonb_typeof(job_item -> 'payload') <> 'object'
       or pg_catalog.btrim(job_item ->> 'bundle_id') !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
  ) then
    return pg_catalog.jsonb_build_object('saved', false, 'reason', 'ocr_job_identity_invalid');
  end if;
  if (
    select count(distinct pg_catalog.jsonb_build_array(
      pg_catalog.btrim(job_item ->> 'tenant_id'),
      pg_catalog.btrim(job_item ->> 'job_key')
    ))
    from pg_catalog.jsonb_array_elements(p_jobs) job_item
  ) <> v_job_count then
    return pg_catalog.jsonb_build_object('saved', false, 'reason', 'ocr_job_identity_duplicate');
  end if;

  with incoming as (
    select
      pg_catalog.btrim(job_item ->> 'tenant_id') as tenant_id,
      pg_catalog.btrim(job_item ->> 'job_key') as job_key,
      pg_catalog.btrim(job_item ->> 'asset_id') as asset_id,
      (pg_catalog.btrim(job_item ->> 'bundle_id'))::uuid as bundle_id,
      greatest(1, least(coalesce((job_item ->> 'priority')::integer, 40), 1000)) as priority,
      job_item -> 'payload' as payload
    from pg_catalog.jsonb_array_elements(p_jobs) job_item
  )
  select count(*)::integer
  into v_identity_mismatch
  from incoming
  join public.preingestion_jobs existing
    on existing.tenant_id = incoming.tenant_id
   and existing.job_key = incoming.job_key
  where existing.asset_id is distinct from incoming.asset_id
     or existing.bundle_id is distinct from incoming.bundle_id
     or existing.job_type is distinct from 'ocr_crop_verification';
  if v_identity_mismatch > 0 then
    raise exception using
      errcode = '23505',
      message = 'recognition_preingestion_ocr_job_identity_conflict';
  end if;

  with incoming as (
    select
      pg_catalog.btrim(job_item ->> 'tenant_id') as tenant_id,
      pg_catalog.btrim(job_item ->> 'job_key') as job_key,
      pg_catalog.btrim(job_item ->> 'asset_id') as asset_id,
      (pg_catalog.btrim(job_item ->> 'bundle_id'))::uuid as bundle_id,
      greatest(1, least(coalesce((job_item ->> 'priority')::integer, 40), 1000)) as priority,
      job_item -> 'payload' as payload
    from pg_catalog.jsonb_array_elements(p_jobs) job_item
  ), inserted as (
    insert into public.preingestion_jobs (
      tenant_id,
      job_key,
      asset_id,
      bundle_id,
      job_type,
      status,
      priority,
      payload,
      created_at,
      updated_at
    )
    select
      incoming.tenant_id,
      incoming.job_key,
      incoming.asset_id,
      incoming.bundle_id,
      'ocr_crop_verification',
      'queued',
      incoming.priority,
      incoming.payload,
      pg_catalog.clock_timestamp(),
      pg_catalog.clock_timestamp()
    from incoming
    on conflict (tenant_id, job_key) do nothing
    returning 1
  )
  select count(*)::integer into v_inserted from inserted;

  if v_retry_lineage <> '' then
    with incoming as (
      select
        pg_catalog.btrim(job_item ->> 'tenant_id') as tenant_id,
        pg_catalog.btrim(job_item ->> 'job_key') as job_key,
        pg_catalog.btrim(job_item ->> 'asset_id') as asset_id,
        (pg_catalog.btrim(job_item ->> 'bundle_id'))::uuid as bundle_id
      from pg_catalog.jsonb_array_elements(p_jobs) job_item
    ), requeued as (
      update public.preingestion_jobs existing
      set status = 'queued',
          attempts = 0,
          last_error = null,
          lease_owner = null,
          lease_expires_at = null,
          payload = existing.payload || pg_catalog.jsonb_build_object(
            'authorized_retry_lineage_id', v_retry_lineage
          ),
          updated_at = pg_catalog.clock_timestamp()
      from incoming
      where existing.tenant_id = incoming.tenant_id
        and existing.job_key = incoming.job_key
        and existing.asset_id = incoming.asset_id
        and existing.bundle_id = incoming.bundle_id
        and existing.job_type = 'ocr_crop_verification'
        and existing.status in ('failed', 'cancelled')
        and existing.lease_owner is null
        and existing.lease_expires_at is null
        and coalesce(existing.payload ->> 'authorized_retry_lineage_id', '') <> v_retry_lineage
      returning 1
    )
    select count(*)::integer into v_requeued from requeued;
  end if;

  with incoming as (
    select
      pg_catalog.btrim(job_item ->> 'tenant_id') as tenant_id,
      pg_catalog.btrim(job_item ->> 'job_key') as job_key,
      pg_catalog.btrim(job_item ->> 'asset_id') as asset_id,
      (pg_catalog.btrim(job_item ->> 'bundle_id'))::uuid as bundle_id
    from pg_catalog.jsonb_array_elements(p_jobs) job_item
  )
  select
    count(*)::integer,
    count(*) filter (where existing.status in ('queued', 'running'))::integer,
    count(*) filter (where existing.status = 'succeeded')::integer,
    count(*) filter (where existing.status in ('failed', 'cancelled'))::integer
  into v_state_count, v_runnable, v_succeeded, v_blocked_terminal
  from incoming
  join public.preingestion_jobs existing
    on existing.tenant_id = incoming.tenant_id
   and existing.job_key = incoming.job_key
   and existing.asset_id = incoming.asset_id
   and existing.bundle_id = incoming.bundle_id
   and existing.job_type = 'ocr_crop_verification';

  return pg_catalog.jsonb_build_object(
    'saved', v_state_count = v_job_count and v_blocked_terminal = 0,
    'reason', case
      when v_state_count <> v_job_count then 'ocr_job_state_missing'
      when v_blocked_terminal > 0 and v_retry_lineage = '' then 'ocr_terminal_retry_authorization_required'
      when v_blocked_terminal > 0 then 'ocr_authorized_retry_lineage_exhausted'
      else null
    end,
    'attempted_count', v_job_count,
    'inserted_count', v_inserted,
    'requeued_count', v_requeued,
    'runnable_count', v_runnable,
    'succeeded_count', v_succeeded,
    'blocked_terminal_count', v_blocked_terminal,
    'authorized_retry_lineage_applied', v_retry_lineage <> '' and v_requeued > 0
  );
end;
$$;

revoke all on function public.enqueue_recognition_preingestion_ocr_jobs(jsonb, text)
  from public, anon, authenticated;
grant execute on function public.enqueue_recognition_preingestion_ocr_jobs(jsonb, text)
  to service_role;

create or replace function public.v4_queue_enqueue_contract_version()
returns text
language sql
stable
security invoker
set search_path = ''
as $$
  select 'v4-queue-identity-outbox-v1'::text;
$$;

revoke all on function public.v4_queue_enqueue_contract_version()
  from public, anon, authenticated;
grant execute on function public.v4_queue_enqueue_contract_version()
  to service_role;

-- Keep the already-audited atomic implementation intact, but place a small
-- fail-closed contract wrapper in front of it. Identical job ids repeated in
-- one p_jobs array otherwise collapse under ON CONFLICT while the requested
-- batch item_count still says two. A different id for the same semantic job is
-- equally invalid and would schedule duplicate paid work without this guard.
do $$
begin
  if pg_catalog.to_regprocedure(
       'public.enqueue_v4_recognition_batch_atomic_impl_20260728(jsonb,jsonb,text,jsonb,text)'
     ) is null then
    alter function public.enqueue_v4_recognition_batch_atomic(jsonb, jsonb, text, jsonb, text)
      rename to enqueue_v4_recognition_batch_atomic_impl_20260728;
  end if;
end;
$$;

revoke all on function public.enqueue_v4_recognition_batch_atomic_impl_20260728(jsonb, jsonb, text, jsonb, text)
  from public, anon, authenticated, service_role;

create or replace function public.enqueue_v4_recognition_batch_atomic(
  p_batch jsonb,
  p_jobs jsonb,
  p_operator_id text,
  p_sessions jsonb,
  p_tenant_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_job_count integer := case
    when pg_catalog.jsonb_typeof(p_jobs) = 'array' then pg_catalog.jsonb_array_length(p_jobs)
    else 0
  end;
  v_distinct_job_id_count integer := 0;
  v_expected_outbox_count integer := 0;
  v_outbox_count integer := 0;
  v_result jsonb;
begin
  if pg_catalog.jsonb_typeof(p_jobs) <> 'array'
     or v_job_count < 1
     or v_job_count > 500 then
    return pg_catalog.jsonb_build_object('saved', false, 'reason', 'invalid_atomic_enqueue_request');
  end if;

  if exists (
    select 1
    from pg_catalog.jsonb_array_elements(p_jobs) job_item
    where pg_catalog.jsonb_typeof(job_item) <> 'object'
       or nullif(pg_catalog.btrim(job_item ->> 'id'), '') is null
       or nullif(pg_catalog.btrim(job_item ->> 'tenant_id'), '') is null
       or nullif(pg_catalog.btrim(job_item ->> 'operator_id'), '') is null
       or nullif(pg_catalog.btrim(job_item ->> 'recognition_session_id'), '') is null
       or nullif(pg_catalog.btrim(job_item ->> 'asset_id'), '') is null
       or nullif(pg_catalog.btrim(job_item ->> 'job_type'), '') is null
       or pg_catalog.jsonb_typeof(job_item -> 'payload') <> 'object'
       -- Expand-phase compatibility: old application instances do not yet
       -- send queue_decision_fingerprint. They keep using the audited legacy
       -- path during the rolling window. Once the new marker is present, the
       -- complete semantic identity is mandatory and fail-closed.
       or (
         nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'queue_decision_fingerprint'), '') is not null
         and (
           nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'image_generation_id'), '') is null
           or nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'image_set_sha256'), '') is null
           or nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'image_set_sha256'), '') !~ '^[0-9a-fA-F]{64}$'
           or nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'queue_decision_fingerprint'), '') !~ '^[0-9a-fA-F]{64}$'
         )
       )
       or (
         nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'authorized_retry_of_job_id'), '') is not null
         and (
           job_item -> 'payload' ->> 'authorized_retry_of_job_id'
             is distinct from job_item -> 'payload' ->> 'retry_of_job_id'
           or coalesce(job_item -> 'payload' ->> 'manual_retry', 'false') <> 'true'
         )
       )
  ) then
    return pg_catalog.jsonb_build_object('saved', false, 'reason', 'job_semantic_identity_invalid');
  end if;

  select count(distinct job_item ->> 'id')::integer
  into v_distinct_job_id_count
  from pg_catalog.jsonb_array_elements(p_jobs) job_item;
  if v_distinct_job_id_count <> v_job_count then
    return pg_catalog.jsonb_build_object('saved', false, 'reason', 'duplicate_job_id');
  end if;

  if exists (
    select 1
    from pg_catalog.jsonb_array_elements(p_jobs) job_item
    where nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'queue_decision_fingerprint'), '') is not null
    group by
      p_tenant_id,
      p_operator_id,
      pg_catalog.btrim(job_item ->> 'asset_id'),
      pg_catalog.btrim(job_item -> 'payload' ->> 'image_generation_id'),
      pg_catalog.lower(pg_catalog.btrim(job_item -> 'payload' ->> 'image_set_sha256')),
      pg_catalog.lower(pg_catalog.btrim(job_item -> 'payload' ->> 'queue_decision_fingerprint')),
      pg_catalog.upper(pg_catalog.btrim(job_item ->> 'job_type')),
      coalesce(nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'authorized_retry_of_job_id'), ''), '')
    having count(*) > 1
  ) then
    return pg_catalog.jsonb_build_object('saved', false, 'reason', 'duplicate_job_semantic_identity');
  end if;

  -- A moving model/catalog/worker revision may not be replayed from a terminal
  -- row. Keep the semantic identity occupied (so nonce changes cannot pay
  -- again) but fail closed until immutable revision readiness is restored.
  if exists (
    select 1
    from pg_catalog.jsonb_array_elements(p_jobs) job_item
    join public.v4_recognition_jobs existing_job
      on existing_job.id = job_item ->> 'id'
    where existing_job.status in ('L1_READY', 'L2_READY')
      and nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'queue_decision_fingerprint'), '') is not null
      and coalesce(job_item -> 'payload' ->> 'queue_decision_replay_ready', 'false') <> 'true'
  ) then
    return pg_catalog.jsonb_build_object(
      'saved', false,
      'reason', 'queue_terminal_replay_revision_not_ready'
    );
  end if;

  select public.enqueue_v4_recognition_batch_atomic_impl_20260728(
    p_batch,
    p_jobs,
    p_operator_id,
    p_sessions,
    p_tenant_id
  ) into v_result;

  if coalesce((v_result ->> 'saved')::boolean, false) then
    select count(*)::integer
    into v_expected_outbox_count
    from (
      select 1
      from pg_catalog.jsonb_array_elements(p_jobs) job_item
      join pg_catalog.jsonb_array_elements(coalesce(v_result -> 'jobs', '[]'::jsonb)) result_item
        on result_item -> 'row' ->> 'id' = job_item ->> 'id'
      where coalesce((result_item ->> 'saved')::boolean, false)
        and pg_catalog.upper(coalesce(result_item -> 'row' ->> 'status', '')) in ('QUEUED', 'RETRYING', 'RUNNING')
        and nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'image_generation_id'), '') is not null
        and nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'image_set_sha256'), '') ~ '^[0-9a-fA-F]{64}$'
        and nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'queue_decision_fingerprint'), '') ~ '^[0-9a-fA-F]{64}$'
      group by
        job_item ->> 'asset_id',
        pg_catalog.btrim(job_item -> 'payload' ->> 'image_generation_id'),
        pg_catalog.lower(pg_catalog.btrim(job_item -> 'payload' ->> 'image_set_sha256')),
        pg_catalog.lower(pg_catalog.btrim(job_item -> 'payload' ->> 'queue_decision_fingerprint')),
        coalesce(nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'authorized_retry_of_job_id'), ''), '')
    ) eligible_outbox_groups;

    insert into public.preingestion_recognition_commit_outbox as outbox (
      tenant_id,
      asset_id,
      image_generation_id,
      image_set_sha256,
      queue_decision_fingerprint,
      identity_result_cache_key,
      identity_cache_image_generation_hash,
      identity_cache_read_allowed,
      writer_final_replay_allowed,
      authorized_retry_of_job_id,
      recognition_batch_id,
      recognition_job_id,
      status,
      next_attempt_at,
      updated_at
    )
    select
      p_tenant_id,
      job_item ->> 'asset_id',
      pg_catalog.btrim(job_item -> 'payload' ->> 'image_generation_id'),
      pg_catalog.lower(pg_catalog.btrim(job_item -> 'payload' ->> 'image_set_sha256')),
      pg_catalog.lower(pg_catalog.btrim(job_item -> 'payload' ->> 'queue_decision_fingerprint')),
      pg_catalog.lower(nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'identity_result_cache_key'), '')),
      pg_catalog.lower(nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'identity_cache_image_generation_hash'), '')),
      pg_catalog.lower(coalesce(
        job_item -> 'payload' -> 'provider_options' ->> 'disable_identity_result_cache',
        'false'
      )) not in ('1', 'true', 'yes', 'on')
        and pg_catalog.lower(coalesce(
          job_item -> 'payload' -> 'provider_options' ->> 'disable_identity_result_cache_read',
          'false'
        )) not in ('1', 'true', 'yes', 'on'),
      pg_catalog.lower(coalesce(
        job_item -> 'payload' -> 'provider_options' ->> 'disable_writer_final_replay',
        'false'
      )) not in ('1', 'true', 'yes', 'on'),
      coalesce(nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'authorized_retry_of_job_id'), ''), ''),
      nullif(pg_catalog.btrim(p_batch ->> 'id'), ''),
      pg_catalog.min(job_item ->> 'id'),
      'queued',
      pg_catalog.clock_timestamp(),
      pg_catalog.clock_timestamp()
    from pg_catalog.jsonb_array_elements(p_jobs) job_item
    join pg_catalog.jsonb_array_elements(coalesce(v_result -> 'jobs', '[]'::jsonb)) result_item
      on result_item -> 'row' ->> 'id' = job_item ->> 'id'
    where coalesce((result_item ->> 'saved')::boolean, false)
      and pg_catalog.upper(coalesce(result_item -> 'row' ->> 'status', '')) in ('QUEUED', 'RETRYING', 'RUNNING')
      and nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'image_generation_id'), '') is not null
      and nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'image_set_sha256'), '') ~ '^[0-9a-fA-F]{64}$'
      and nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'queue_decision_fingerprint'), '') ~ '^[0-9a-fA-F]{64}$'
    group by
      job_item ->> 'asset_id',
      pg_catalog.btrim(job_item -> 'payload' ->> 'image_generation_id'),
      pg_catalog.lower(pg_catalog.btrim(job_item -> 'payload' ->> 'image_set_sha256')),
      pg_catalog.lower(pg_catalog.btrim(job_item -> 'payload' ->> 'queue_decision_fingerprint')),
      pg_catalog.lower(nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'identity_result_cache_key'), '')),
      pg_catalog.lower(nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'identity_cache_image_generation_hash'), '')),
      pg_catalog.lower(coalesce(job_item -> 'payload' -> 'provider_options' ->> 'disable_identity_result_cache', 'false')),
      pg_catalog.lower(coalesce(job_item -> 'payload' -> 'provider_options' ->> 'disable_identity_result_cache_read', 'false')),
      pg_catalog.lower(coalesce(job_item -> 'payload' -> 'provider_options' ->> 'disable_writer_final_replay', 'false')),
      coalesce(nullif(pg_catalog.btrim(job_item -> 'payload' ->> 'authorized_retry_of_job_id'), ''), '')
    on conflict (
      tenant_id,
      asset_id,
      image_generation_id,
      image_set_sha256,
      queue_decision_fingerprint,
      authorized_retry_of_job_id
    )
    do update set
      recognition_batch_id = excluded.recognition_batch_id,
      recognition_job_id = excluded.recognition_job_id,
      identity_result_cache_key = coalesce(outbox.identity_result_cache_key, excluded.identity_result_cache_key),
      identity_cache_image_generation_hash = coalesce(
        outbox.identity_cache_image_generation_hash,
        excluded.identity_cache_image_generation_hash
      ),
      identity_cache_read_allowed = outbox.identity_cache_read_allowed and excluded.identity_cache_read_allowed,
      writer_final_replay_allowed = outbox.writer_final_replay_allowed and excluded.writer_final_replay_allowed,
      status = case
        when outbox.status in ('completed', 'processing', 'dead_letter') then outbox.status
        else 'queued'
      end,
      next_attempt_at = case
        when outbox.status in ('completed', 'processing', 'dead_letter') then outbox.next_attempt_at
        else pg_catalog.clock_timestamp()
      end,
      lease_owner = case when outbox.status = 'processing' then outbox.lease_owner else null end,
      lease_expires_at = case when outbox.status = 'processing' then outbox.lease_expires_at else null end,
      last_error = case when outbox.status in ('completed', 'processing', 'dead_letter') then outbox.last_error else null end,
      updated_at = pg_catalog.clock_timestamp()
    where (outbox.identity_result_cache_key is null
        or excluded.identity_result_cache_key is null
        or outbox.identity_result_cache_key = excluded.identity_result_cache_key)
      and (outbox.identity_cache_image_generation_hash is null
        or excluded.identity_cache_image_generation_hash is null
        or outbox.identity_cache_image_generation_hash = excluded.identity_cache_image_generation_hash);
    get diagnostics v_outbox_count = row_count;
    if v_outbox_count <> v_expected_outbox_count then
      raise exception using
        errcode = '23505',
        message = 'preingestion_recognition_outbox_identity_conflict';
    end if;
  end if;
  return v_result || pg_catalog.jsonb_build_object(
    'queue_enqueue_contract_version', 'v4-queue-identity-outbox-v1',
    'preingestion_commit_intent_count', v_outbox_count
  );
end;
$$;

revoke all on function public.enqueue_v4_recognition_batch_atomic(jsonb, jsonb, text, jsonb, text)
  from public, anon, authenticated;
grant execute on function public.enqueue_v4_recognition_batch_atomic(jsonb, jsonb, text, jsonb, text)
  to service_role;

comment on function public.enqueue_v4_recognition_batch_atomic(jsonb, jsonb, text, jsonb, text) is
  'Service-role atomic enqueue boundary. Expand-phase compatible with old jobs; v4-queue-identity-outbox-v1 jobs receive atomic durable OCR intent.';

notify pgrst, 'reload schema';

commit;
